Repository grafana/plugin-tools, pull requests merged in 2022-12, with the labels that each got.

#169 Docs: Introduce Docusaurus website
  .github/workflows/deploy.yml
  .github/workflows/test-build.yml
  .gitignore
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/backend.md
  docusaurus/docs/ci.md
  docusaurus/docs/distributing-your-plugin.md
  docusaurus/docs/docker.md
  docusaurus/docs/e2e-tests.md
  docusaurus/docs/editor-setup.md
  docusaurus/docs/folder-structure.md
  docusaurus/docs/frontend.md
  docusaurus/docs/getting-started.md
  docusaurus/docs/production-builds.md
  docusaurus/docs/unit-tests.md
  docusaurus/docs/updating-to-new-releases.md
  docusaurus/website/README.md
  docusaurus/website/babel.config.js
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/sidebars.js
  docusaurus/website/src/components/HomepageFeatures/index.tsx
  docusaurus/website/src/components/HomepageFeatures/styles.module.css
  docusaurus/website/src/components/HomepageGettingStarted/index.tsx
  docusaurus/website/src/components/HomepageGettingStarted/styles.module.css
  docusaurus/website/src/css/custom.css
  docusaurus/website/src/pages/homepage_logo.svg
  docusaurus/website/src/pages/index.module.css
  docusaurus/website/src/pages/index.tsx
  docusaurus/website/src/pages/markdown-page.md
  docusaurus/website/static/.nojekyll
  docusaurus/website/static/img/favicon.png
  docusaurus/website/static/img/homepage_gettingstarted.gif
  docusaurus/website/static/img/homepage_update.gif
  docusaurus/website/static/img/logo.svg
  docusaurus/website/tsconfig.json
  package.json
  yarn.lock
Labels: documentation

#173 Templates: Use getDefaultQuery method to set query default values
  packages/create-plugin/templates/backend/src/datasource.ts
  packages/create-plugin/templates/datasource/src/components/QueryEditor.tsx
  packages/create-plugin/templates/datasource/src/datasource.ts
  packages/create-plugin/templates/datasource/src/types.ts
Labels: enhancement, patch, release

#176 Adding google search console verification file
  docusaurus/website/static/google33723ad8dc697437.html
Labels: documentation, chore
