Repository grafana/plugin-tools, pull requests merged in 2022-10, with the labels that each got.

#68 Migrate: Sort package.json fields
  src/commands/migrate.command.ts
  src/utils/utils.npm.ts
Labels: enhancement

#59 Updates README about creating a new plugin
  README.md
Labels: documentation

#66 Templates: Set timezone to UTC for jest
  templates/common/jest.config.js
Labels: bug

#67 Templates: Use plugincheck2 in release workflow
  templates/github/ci/.github/workflows/release.yml
Labels: enhancement

#76 Chore: Refresh yarn.lock file (removes unused grafana/data)
  yarn.lock
Labels: dependencies

#75 Do not use TS_NODE_PROJECT for webpack configuration
  packages/create-plugin/templates/common/.config/README.md
  packages/create-plugin/templates/common/.config/tsconfig.json
  packages/create-plugin/templates/common/.config/webpack/tsconfig.webpack.json
  packages/create-plugin/templates/common/package.json
Labels: bug

#78 Fix npm bump running test
  .github/workflows/npm-bump-version.yml
Labels: bug

#81 Add e2e to CI workflow
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
Labels: enhancement

#85 Prevent webpack to clean binaries from go
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: enhancement

#88 Update backend versions
  packages/create-plugin/templates/backend/go.mod
  packages/create-plugin/templates/backend/go.sum
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
Labels: enhancement, create-plugin

#89 Do not generate or ask to generate a backend in panel plugins
  packages/create-plugin/package.json
  packages/create-plugin/scripts/generate-app.js
  packages/create-plugin/scripts/generate-datasource.js
  packages/create-plugin/scripts/generate-panel.js
  packages/create-plugin/src/commands/generate.plopfile.ts
Labels: enhancement

#83 Docs: Update docs for monorepo changes
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  package.json
  packages/create-plugin/CONTRIBUTING.md
  packages/create-plugin/README.md
  packages/create-plugin/package.json
  packages/create-plugin/src/constants.ts
  packages/sign-plugin/CONTRIBUTING.md
  packages/sign-plugin/LICENSE
  packages/sign-plugin/README.md
  packages/sign-plugin/package.json
Labels: documentation

#93 Add missing keywords field to plugin.json
  packages/create-plugin/templates/app/src/plugin.json
  packages/create-plugin/templates/panel/src/plugin.json
Labels: enhancement

#94 Change update prompt message to clarify what is updating
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/constants.ts
Labels: bug

#100 Bumping nodemon to fix https://github.com/grafana/plugin-tools/security/dependabot/3
  yarn.lock
Labels: dependencies

#104 Fix: Make sure webpack and jest can resolve "rootDir" paths
  packages/create-plugin/templates/common/.config/jest.config.js
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin

#98 App: disable backend by default in yarn generate-app
  packages/create-plugin/scripts/generate-app.js
Labels: create-plugin

#103 Feature: Support for css/sass files
  packages/create-plugin/templates/common/.config/jest.config.js
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
  packages/create-plugin/templates/common/package.json
Labels: enhancement, create-plugin

#106 Fix: Don't ignore node_modules css files
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin

#105 Remove scripts refering grafana-toolkit when migrating and updating
  packages/create-plugin/src/constants.ts
  packages/create-plugin/src/utils/utils.npm.ts
Labels: enhancement

#107 Update post-migration message
  packages/create-plugin/src/constants.ts
Labels: documentation, enhancement

#108 Jest: Ignore ol library
  packages/create-plugin/templates/common/.config/jest.config.js
Labels: bug, create-plugin

#109 Use normalize_id for docker-compose.yml instead of only pluginName
  packages/create-plugin/src/utils/utils.handlebars.ts
  packages/create-plugin/templates/common/docker-compose.yaml
Labels: enhancement

#110 Updating app template to use compatible icon
  packages/create-plugin/templates/app/src/module.ts
Labels: create-plugin

#112 Instruct jest to transform all packages (including all inside node_modules)
  packages/create-plugin/templates/common/.config/jest.config.js
Labels: bug

#117 Sign-Plugin: Clean up, improve error messages, add basic CI steps
  .github/workflows/test.yml
  packages/sign-plugin/src/bin/run.ts
  packages/sign-plugin/src/commands/sign.command.ts
  packages/sign-plugin/src/utils/getVersion.ts
  packages/sign-plugin/src/utils/manifest.ts
Labels: enhancement, sign-plugin

#119 Create-Plugin: Ignore grafana dependencies when migrating
  packages/create-plugin/src/commands/migrate.command.ts
  packages/create-plugin/src/constants.ts
  packages/create-plugin/src/utils/utils.npm.ts
Labels: dependencies, create-plugin

#123 Add a manual mock for react-inlinesvg to prevent errors when running test with grafana-ui and icons
  packages/create-plugin/templates/common/.config/jest.config.js
  packages/create-plugin/templates/common/.config/mocks/react-inlinesvg.tsx
Labels: bug

#126 Manually rename gitignore to prevent yarn and npm pack from removing them
  packages/create-plugin/src/commands/generate.plopfile.ts
  packages/create-plugin/templates/common/gitignore
Labels: bug

#127 CI: Introduce auto for publishing packages
  .all-contributorsrc
  .autorc
  .github/workflows/ci.yml
  .github/workflows/create-release.yml
  .github/workflows/npm-bump-version.yml
  CONTRIBUTING.md
  README.md
  lerna.json
  package.json
  packages/create-plugin/package.json
  packages/sign-plugin/package.json
  yarn.lock
Labels: documentation, dependencies, patch, release
