Repository grafana/plugin-tools, pull requests merged in 2023-07, with the labels that each got.

#289 Create Plugin: Add rxjs and schema to known Jest ES modules
  packages/create-plugin/templates/common/.config/jest/utils.js
Labels: create-plugin, patch, release, chore

#293 Website: Update Docusaurus config post Grafana docs update
  docusaurus/website/docusaurus.config.js
Labels: documentation, no-changelog

#294 Docs: Update readme and contributing to use NPM
  docusaurus/website/README.md
  packages/create-plugin/CONTRIBUTING.md
  packages/sign-plugin/CONTRIBUTING.md
Labels: documentation, no-changelog

#292 Chore: Remove axios as a dependency for sign-plugin
  package-lock.json
  packages/sign-plugin/package.json
  packages/sign-plugin/src/utils/manifest.ts
  packages/sign-plugin/src/utils/request.ts
Labels: sign-plugin, patch, release, chore

#298 Create Plugin: add readme best practice example
  packages/create-plugin/templates/common/src/README.md
Labels: create-plugin, minor

#287 Create Plugin: Update scenes to latest version
  packages/create-plugin/templates/common/package.json
  packages/create-plugin/templates/scenes-app/src/pages/HelloWorld/helloWorldScene.tsx
  packages/create-plugin/templates/scenes-app/src/pages/Home/scenes.tsx
  packages/create-plugin/templates/scenes-app/src/pages/WithDrilldown/panels.tsx
  packages/create-plugin/templates/scenes-app/src/pages/WithDrilldown/scenes.tsx
Labels: patch, release

#296 Docs: Plugin migration - 4 intro docs
  docusaurus/docs/introduction/backend.md
  docusaurus/docs/introduction/data-frames.md
  docusaurus/docs/introduction/grafana-plugin-sdk-for-go.md
  docusaurus/docs/introduction/plugin-protocol.md
  docusaurus/website/sidebars.js
Labels: documentation, no-changelog

#307 Docs: Remove Docusaurus remote content plugin
  .gitignore
  docusaurus/docs/signing-your-plugin.md
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  package-lock.json
Labels: documentation, chore, no-changelog

#311 Website: Add shared alias for includes
  docusaurus/website/docusaurus.config.js
Labels: documentation, no-changelog

#312 Website: Introduce captions for images
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/src/css/custom.css
  package-lock.json
Labels: documentation, no-changelog

#315 (chore): add top level license file
  LICENSE
Labels: chore, no-changelog

#317 (chore): migrate to autogen sidebar
  docusaurus/docs/advanced-usage/_category_.json
  docusaurus/docs/advanced-usage/advanced-configuration.md
  docusaurus/docs/advanced-usage/nested-plugins.mdx
  docusaurus/docs/development/_category_.json
  docusaurus/docs/development/backend.md
  docusaurus/docs/development/ci.md
  docusaurus/docs/development/docker.mdx
  docusaurus/docs/development/frontend.mdx
  docusaurus/docs/distribution/_category_.json
  docusaurus/docs/distribution/distributing-your-plugin.md
  docusaurus/docs/distribution/signing-your-plugin.md
  docusaurus/docs/drafts/_category_.json
  docusaurus/docs/drafts/e2e-tests.md
  docusaurus/docs/drafts/editor-setup.md
  docusaurus/docs/drafts/production-builds.md
  docusaurus/docs/drafts/unit-tests.md
  docusaurus/docs/getting-started/_category_.json
  docusaurus/docs/getting-started/creating-a-plugin.mdx
  docusaurus/docs/getting-started/folder-structure.md
  docusaurus/docs/getting-started/getting-started.mdx
  docusaurus/docs/getting-started/migrating-from-toolkit.mdx
  docusaurus/docs/getting-started/updating-to-new-releases.mdx
  docusaurus/docs/introduction/_category_.json
  docusaurus/docs/introduction/backend.md
  docusaurus/docs/introduction/data-frames.md
  docusaurus/docs/introduction/grafana-plugin-sdk-for-go.md
  docusaurus/docs/introduction/plugin-protocol.md
  docusaurus/docs/snippets/_category_.json
  docusaurus/website/docusaurus.config.js
  docusaurus/website/sidebars.js
Labels: documentation, chore, no-changelog
