Repository grafana/plugin-tools, pull requests merged in 2023-12, with the labels that each got.

#573 Update the scenes-app template to use the latest scenes library and fix some template code style errors
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/scenes-app/src/components/App/App.tsx
  packages/create-plugin/templates/scenes-app/src/components/AppConfig/AppConfig.tsx
  packages/create-plugin/templates/scenes-app/src/components/Routes/Routes.tsx
Labels: create-plugin, minor, release

#578 Adding codeowners
  .github/CODEOWNERS
Labels: chore, no-changelog, github_actions, skip-release

#455 Update react to 18 in package.json template
  packages/create-plugin/templates/common/_package.json
Labels: create-plugin, patch, release

#579 Docs: Mention new command palette extension point and add example
  docusaurus/docs/ui-extensions/register-an-extension.md
Labels: type/docs, no-changelog

#580 CI: Remove custom npm cache for generated plugins
  .github/workflows/ci.yml
Labels: chore, no-changelog

#539 Website: Update prism syntax highlighter theme
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/src/theme/prism.js
Labels: chore, no-changelog

#581 Plugin E2E: Enable testing the query editor in Explore
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/explorePage.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/GrafanaPage.ts
  packages/plugin-e2e/src/models/TimeRange.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/datasource/explore/queryEditor.spec.ts
Labels: no-changelog

#582 Chore: Group updates to docusaurus dependencies
  .github/dependabot.yml
  .github/workflows/test-build.yml
Labels: chore, no-changelog

#577 Plugin E2E: Enable testing the annotation editor
  docusaurus/docs/ui-extensions/register-an-extension.md
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/annotationEditPage.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/models/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/AnnotationPage.ts
  packages/plugin-e2e/src/models/index.ts
  packages/plugin-e2e/tests/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/datasource/annotations/annotationQueryRunner.integration.spec.ts
Labels: no-changelog

#583 Minor edits to style of README.md
  packages/create-plugin/templates/app/README.md
Labels: type/docs, patch

#556 Add best practices doc
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
Labels: no-changelog

#374 Copy over `query_help.md` when building plugins
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, patch, release

#592 Update docs for plugin submission form
  docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
  docusaurus/website/static/img/plugins-submission-create.png
  docusaurus/website/static/img/plugins-submission-create2.png
Labels: no-changelog

#596 Chore: Bump Auto npm packages to ^11.x.x
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: chore, no-changelog

#594 Plugin-E2E: Refactor models
  packages/plugin-e2e/src/fixtures/annotationEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSourceConfigPage.ts
  packages/plugin-e2e/src/fixtures/explorePage.ts
  packages/plugin-e2e/src/fixtures/newDashboardPage.ts
  packages/plugin-e2e/src/fixtures/variableEditPage.ts
  packages/plugin-e2e/src/models/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/AnnotationPage.ts
  packages/plugin-e2e/src/models/DashboardPage.ts
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
  packages/plugin-e2e/src/models/DataSourcePicker.ts
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/GrafanaPage.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/models/TimeRange.ts
  packages/plugin-e2e/src/models/VariableEditPage.ts
  packages/plugin-e2e/src/models/VariablePage.ts
Labels: no-changelog

#597 Plugin E2E: Replace magic strings with selectors
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSource.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSourceConfigPage.ts
  packages/plugin-e2e/src/models/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/AnnotationPage.ts
  packages/plugin-e2e/src/models/DashboardPage.ts
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/GrafanaPage.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/models/TimeRange.ts
  packages/plugin-e2e/src/models/VariablePage.ts
  packages/plugin-e2e/tests/datasource/variables/customVariableEditor.spec.ts
Labels: no-changelog

#605 Plugin E2E: Publish to NPM
  packages/plugin-e2e/package.json
Labels: patch, release, plugin-e2e

#608 Plugin E2E: Use module nodenext
  packages/plugin-e2e/tsconfig.json
Labels: patch, release

#610 Plugin E2E: Add expect matcher for alert box
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
  packages/plugin-e2e/src/matchers/index.ts
  packages/plugin-e2e/src/matchers/toHaveAlert.ts
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/datasource/configEditor.spec.ts
Labels: patch, release

#611 Plugin E2E: Use E2E version action
  .github/workflows/playwright.yml
Labels: no-changelog

#612 Plugin E2E: Add isFeatureToggleEnabled fixture
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/fixtures/isFeatureToggleEnabled.ts
  packages/plugin-e2e/src/models/GrafanaPage.ts
  packages/plugin-e2e/tests/datasource/featuretoggles/queryDataHandler.spec.ts
Labels: patch, release

#603 Plugin E2E: Harmonise model instantiation and navigation
  packages/plugin-e2e/CHANGELOG.md
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/models/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/AnnotationPage.ts
  packages/plugin-e2e/src/models/DashboardPage.ts
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
  packages/plugin-e2e/src/models/GrafanaPage.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/models/VariableEditPage.ts
  packages/plugin-e2e/src/models/VariablePage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/datasource/variables/customVariableEditor.spec.ts
  packages/plugin-e2e/tests/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/datasource/variables/variableInterpolation.spec.ts
Labels: minor, release

#618 Revert "Chore: Bump Auto npm packages to ^11.x.x"
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: chore, no-changelog

#614 Plugin-E2E: Keep comments in tsd files
  packages/plugin-e2e/tsconfig.json
Labels: minor, release

#609 Enhance plugin dev best practices doc
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
Labels: type/docs, no-changelog

#547 Docs: Instrument a backend plugin
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-distributed-tracing-for-backend-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-logs-metrics-traces-for-backend-plugins.md
  docusaurus/docs/introduction/backend.md
Labels: type/docs, no-changelog

#613 Add selector to 'Work with frontend components'
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-frontend.mdx
  docusaurus/docs/snippets/createplugin-frontend-npm.md
  docusaurus/docs/snippets/createplugin-frontend-pnpm.md
  docusaurus/docs/snippets/createplugin-frontend-yarn.md
Labels: type/docs, no-changelog
