Repository grafana/plugin-tools, pull requests merged in 2023-09, with the labels that each got.

#381 Move to underscore from dots in urls
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.0.x-v10.1.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v6.x-v7.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.3.x-8.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.x-v9.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.1.x-v9.2.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.3.x-9.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md
Labels: documentation

#382 chore: update links to developer portal
  docusaurus/docs/get-started/get-started.mdx
  packages/create-plugin/README.md
  packages/create-plugin/src/commands/generate-actions/print-success-message.ts
  packages/create-plugin/src/constants.ts
  packages/create-plugin/templates/common/.config/.eslintrc
  packages/create-plugin/templates/common/.config/jest-setup.js
  packages/create-plugin/templates/common/.config/jest.config.js
  packages/create-plugin/templates/common/.config/tsconfig.json
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
  packages/create-plugin/templates/scenes-app/README.md
Labels: documentation, patch, chore

#394 Adding dependabot for github actions
  .github/dependabot.yml
Labels: no-changelog

#402 Changed so UI extensions section isnt collapsed by default
  docusaurus/docs/ui-extensions/_category_.json
Labels: documentation

#373 Docs: update plugins tutorials
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-backend-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin-with-d3.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-streaming-data-source-plugin.md
  docusaurus/docs/shared/create-plugin-backend.md
  docusaurus/docs/shared/create-plugin-frontend.md
  docusaurus/docs/shared/create-plugin.md
  docusaurus/docs/shared/plugin-anatomy.md
  docusaurus/docs/shared/set-up-environment.md
  docusaurus/docs/snippets/docker-grafana-version.npm.md
  docusaurus/docs/snippets/docker-grafana-version.pnpm.md
  docusaurus/docs/snippets/docker-grafana-version.yarn.md
  docusaurus/website/static/img/create-alert.png
Labels: documentation

#404 Update index.md
  docusaurus/docs/ui-extensions/index.md
Labels: documentation

#403 docs: publish tutorials
  docusaurus/docs/tutorials/_category_.json
  docusaurus/docs/tutorials/build-a-data-source-backend-plugin.md
  docusaurus/docs/tutorials/build-a-data-source-plugin.md
  docusaurus/docs/tutorials/build-a-logs-data-source-plugin.md
  docusaurus/docs/tutorials/build-a-panel-plugin-with-d3.md
  docusaurus/docs/tutorials/build-a-panel-plugin.md
  docusaurus/docs/tutorials/build-a-streaming-data-source-plugin.md
Labels: documentation

#364 docs: make signature table more readable
  docusaurus/docs/publish-a-plugin/sign-a-plugin.md
Labels: documentation, no-changelog

#405 Increase required node engine to v18
  .github/workflows/ci.yml
  package-lock.json
  package.json
  packages/create-plugin/package.json
  packages/create-plugin/templates/common/package.json
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
  packages/create-plugin/templates/github/ci/.github/workflows/release.yml
  packages/create-plugin/templates/github/is-compatible/.github/workflows/is-compatible.yml
  packages/sign-plugin/package.json
Labels: chore

#407 Docs: move error handling topic
  docusaurus/docs/create-a-plugin/extend-a-plugin/error-handling.md
Labels: documentation

#408 Docs: fix typo on get-started.mdx
  docusaurus/docs/get-started/get-started.mdx
Labels: documentation

#412 docs: remove scenes public preview caveat
  docusaurus/docs/get-started/get-started.mdx
Labels: documentation

#415 docs: update pre-reqs
  docusaurus/docs/get-started/get-started.mdx
Labels: documentation, no-changelog

#414 webpack template: minor lint fixes
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, patch, type/bug

#413 Docs: Add three indexes as temporary landing pages
  docusaurus/docs/introduction/index.md
  docusaurus/docs/migration-guides/index.md
  docusaurus/docs/tutorials/index.md
Labels: documentation, no-changelog

#416 docs: add docker advice
  docusaurus/docs/troubleshooting.md
Labels: documentation, no-changelog

#425 docs: update api key to access policy token
  docusaurus/docs/publish-a-plugin/sign-a-plugin.md
Labels: documentation, no-changelog
