Repository grafana/plugin-tools, pull requests merged in 2023-08, with the labels that each got.

#295 Adding gcs pipeline
  .github/workflows/deploy-to-developer-portal.yml
  docusaurus/website/docusaurus.config.devportal.js
Labels: chore

#332 Chore/fix dev portal deployment
  .github/workflows/deploy-to-developer-portal.yml
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/website/docusaurus.config.devportal.js
Labels: chore

#334 Website: Re-theme to match Saga design
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/docusaurus.config.devportal.js
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/src/components/HomepageFeatures/index.tsx
  docusaurus/website/src/components/HomepageFeatures/styles.module.css
  docusaurus/website/src/components/HomepageGettingStarted/index.tsx
  docusaurus/website/src/css/custom.css
  docusaurus/website/src/css/theme.css
  docusaurus/website/src/pages/homepage_logo.svg
  docusaurus/website/src/pages/index.module.css
  docusaurus/website/src/pages/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/CollapseButton/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/CollapseButton/styles.module.css
  docusaurus/website/src/theme/DocSidebar/Desktop/Content/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/Content/styles.module.css
  docusaurus/website/src/theme/DocSidebar/Desktop/index.tsx
  docusaurus/website/src/theme/DocSidebar/Desktop/styles.module.css
  docusaurus/website/src/theme/DocSidebar/Mobile/index.tsx
  docusaurus/website/src/theme/DocSidebar/index.tsx
  docusaurus/website/src/theme/prism.js
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa0ZL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1pL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2JL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2ZL7SUc.woff2
  docusaurus/website/static/font/inter/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa2pL7SUc.woff2
  docusaurus/website/static/font/roboto/L0xTDF4xlVMF-BfR8bXMIhJHg45mwgGEFl0_3vrtSM1J-gEPT5Ese6hmHSh0mQ.woff2
  docusaurus/website/static/img/hero_banner.png
  docusaurus/website/static/img/logo.svg
  package-lock.json
Labels: documentation, no-changelog

#336 Website: Fix footer links for dev portal
  docusaurus/website/docusaurus.config.devportal.js
Labels: documentation, no-changelog

#337 Website: fix link and config for dev portal deploy
  .github/workflows/test-build.yml
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/website/docusaurus.config.devportal.js
  package.json
Labels: documentation, no-changelog

#341 Switching to dev bucket and manual dev workflow triggers
  .github/workflows/deploy-to-developer-portal-dev.yml
  docusaurus/website/docusaurus.config.devportal.js
Labels: chore, no-changelog

#340 docs: fix missing link
  docusaurus/docs/introduction/grafana-plugin-sdk-for-go.md
Labels: documentation, no-changelog

#345 prod deployment
  .github/workflows/deploy-to-developer-portal-prod.yml
  docusaurus/website/docusaurus.config.devportal.prod.js
Labels: chore

#342 CI: Remove GH page test and deploy workflows
  .github/workflows/deploy.yml
  .github/workflows/test-build.yml
Labels: chore, no-changelog

#346 Fix swc-core version to 1.3.75 to prevent existing bug with baseUrls
  packages/create-plugin/templates/common/package.json
Labels: create-plugin, patch, release, type/bug

#327 (chore): change FR to issue
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: chore, no-changelog

#349 Docs: Fix link in backend topic
  docusaurus/docs/create-a-plugin/backend.md
Labels: documentation, no-changelog

#351 Docs: add 'error-handling.md' file
  docusaurus/docs/introduction/error-handling.md
  docusaurus/website/static/img/panel_error.png
Labels: documentation, no-changelog

#326 Docs: add migration guide from developers/plugins to plugin-tools repo
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/migration-guides/_category_.json
  docusaurus/docs/migration-guides/angular-react.md
  docusaurus/docs/migration-guides/migrate-from-toolkit.mdx
  docusaurus/docs/migration-guides/update-create-plugin-versions.mdx
  docusaurus/docs/migration-guides/update-from-grafana-versions/_category_.json
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.0.x-v10.1.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v6.x-v7.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.3.x-8.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.x-v9.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.1.x-v9.2.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.3.x-9.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md
  packages/create-plugin/README.md
Labels: documentation, no-changelog

#356 create-plugin: Enable webpack watchOption -> poll if WSL is detected
  packages/create-plugin/templates/common/.config/webpack/utils.ts
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, minor, release

#359 Removing landing page and reshuffling docs
  .github/workflows/deploy-to-developer-portal-dev.yml
  .github/workflows/deploy-to-developer-portal-prod.yml
  .github/workflows/test-build.yml
  docusaurus/docs/create-a-plugin/set-up-github-workflows.md
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/migration-guides/migrate-from-toolkit.mdx
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/docusaurus.config.dev.js
  docusaurus/website/docusaurus.config.devportal.prod.js
  docusaurus/website/docusaurus.config.js
  docusaurus/website/src/pages/index.tsx
Labels: documentation, no-changelog

#352 Docs: add metadata (plugin.json) reference
  docusaurus/docs/metadata.md
Labels: documentation, no-changelog

#357 Docs: Edit Troubleshooting topic
  docusaurus/docs/create-a-plugin/extend-configurations.md
  docusaurus/docs/faq-troubleshoot.md
  docusaurus/docs/troubleshooting.md
Labels: documentation, no-changelog

#350 Docs: Add files in publishing folder to plugin-tools
  docusaurus/docs/create-a-plugin/set-up-github-workflows.md
  docusaurus/docs/get-started/set-up-development-environment.mdx
  docusaurus/docs/publish-a-plugin/distribute-a-plugin.md
  docusaurus/docs/publish-a-plugin/package-a-plugin.md
  docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
  docusaurus/docs/publish-a-plugin/publishing-and-signing-criteria.md
  docusaurus/docs/publish-a-plugin/sign-a-plugin.md
  docusaurus/website/static/img/create-access-policy-token.png
  docusaurus/website/static/img/create-access-policy-v2.png
  docusaurus/website/static/img/plugins-submission-create2.png
Labels: documentation, no-changelog

#363 Adding the noindex back until we start redirecting
  docusaurus/website/docusaurus.config.base.js
Labels: documentation, no-changelog

#354 Add troubleshooting.md page for windows and other create-plugin issues
  docusaurus/docs/create-a-plugin/extend-configurations.md
  docusaurus/docs/troubleshooting.md
Labels: documentation

#333 Docs: Add files from create-a-plugin/extend-a-plugin to plugin-tools
  docusaurus/docs/create-a-plugin/develop-a-plugin/_category_.json
  docusaurus/docs/create-a-plugin/develop-a-plugin/manage-go.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/set-up-github-workflows.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-backend.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-frontend.mdx
  docusaurus/docs/create-a-plugin/extend-a-plugin/_category_.json
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-anonymous-usage-reporting.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-distributed-tracing-for-backend-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-query-editor-help.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-support-for-explore-queries.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-support-for-variables.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/cross-plugin-linking.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/custom-panel-option-editors.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/enable-annotations.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/extend-configurations.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/extend-the-grafana-ui-with-links.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/nested-plugins.mdx
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/introduction/data-frames.md
  docusaurus/docs/migration-guides/migrate-from-toolkit.mdx
Labels: documentation, no-changelog

#335 Docs: Add create-a-plugin/develop-a-plugin content from Hugo site
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-backend-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-logs-data-source-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin-with-d3.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-streaming-data-source-plugin.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/_category_.json
  docusaurus/docs/shared/create-plugin.md
  docusaurus/docs/shared/plugin-anatomy.md
  docusaurus/docs/shared/set-up-environment.md
Labels: documentation, no-changelog

#368 Docs: Delete file that is duplicate of work-with-backend.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/manage-go.md
Labels: documentation, no-changelog

#367 Docs: change link target for plugin.json
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-data-source-backend-plugin.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-logs-data-source-plugin.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/enable-annotations.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
  docusaurus/docs/shared/plugin-anatomy.md
  packages/create-plugin/templates/_partials/distributing-your-plugin.md
  packages/create-plugin/templates/app/README.md
  packages/create-plugin/templates/datasource/README.md
  packages/create-plugin/templates/panel/README.md
Labels: documentation, no-changelog

#369 Docs: update logs data source tutorial
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-logs-data-source-plugin.md
Labels: documentation, no-changelog

#365 create-plugin: Add link to documentation about troubleshooting create-plugin on windows
  packages/create-plugin/src/bin/run.ts
Labels: create-plugin, minor, release

#370 Docs: Fix mismatches between doc titles and H1s
  docusaurus/docs/introduction/error-handling.md
  docusaurus/docs/metadata.md
  docusaurus/docs/migration-guides/angular-react.md
  docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
  docusaurus/docs/publish-a-plugin/publishing-and-signing-criteria.md
Labels: documentation, no-changelog

#371 Docs: Cleanup metadata and improve consistency
  docusaurus/docs/create-a-plugin/develop-a-plugin/build-a-panel-plugin-with-d3.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/set-up-github-workflows.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-backend.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-frontend.mdx
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-support-for-explore-queries.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-support-for-variables.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/cross-plugin-linking.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/extend-the-grafana-ui-with-links.md
  docusaurus/docs/get-started/folder-structure.md
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/get-started/set-up-development-environment.mdx
  docusaurus/docs/introduction/backend.md
  docusaurus/docs/introduction/data-frames.md
  docusaurus/docs/introduction/error-handling.md
  docusaurus/docs/introduction/grafana-plugin-sdk-for-go.md
  docusaurus/docs/introduction/plugin-protocol.md
  docusaurus/docs/metadata.md
  docusaurus/docs/migration-guides/angular-react.md
  docusaurus/docs/migration-guides/migrate-from-toolkit.mdx
  docusaurus/docs/migration-guides/update-create-plugin-versions.mdx
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.0.x-v10.1.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v6.x-v7.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.3.x-8.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.x-v9.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.1.x-v9.2.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.3.x-9.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md
  docusaurus/docs/publish-a-plugin/package-a-plugin.md
  docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
  docusaurus/docs/publish-a-plugin/publishing-and-signing-criteria.md
  docusaurus/docs/publish-a-plugin/sign-a-plugin.md
  docusaurus/docs/troubleshooting.md
Labels: documentation, no-changelog

#375 Update transform regex to detect nested modules
  packages/create-plugin/templates/common/.config/jest/utils.js
Labels: create-plugin, patch, release, type/bug

#377 Docs: Add portal home links
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/docusaurus.config.dev.js
  docusaurus/website/docusaurus.config.js
  docusaurus/website/src/css/custom.css
Labels: documentation, no-changelog

#378 Website: Introduce Search
  docusaurus/website/README.md
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/package.json
  docusaurus/website/src/css/custom.css
  package-lock.json
Labels: documentation, no-changelog
