Repository grafana/plugin-tools, pull requests merged in 2023-05, with the labels that each got.

#233 Website: Introduce Snippets for FE Package Managers
  docusaurus/docs/creating-a-plugin.mdx
  docusaurus/docs/distributing-your-plugin.md
  docusaurus/docs/docker.mdx
  docusaurus/docs/frontend.mdx
  docusaurus/docs/getting-started.mdx
  docusaurus/docs/migrating-from-toolkit.mdx
  docusaurus/docs/nested-plugins.mdx
  docusaurus/docs/snippets/createplugin-install.npm.shell.md
  docusaurus/docs/snippets/createplugin-install.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-install.yarn.shell.md
  docusaurus/docs/snippets/createplugin-migrate.npm.shell.md
  docusaurus/docs/snippets/createplugin-migrate.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-migrate.yarn.shell.md
  docusaurus/docs/snippets/createplugin-scaffold.npm.shell.md
  docusaurus/docs/snippets/createplugin-scaffold.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-scaffold.yarn.shell.md
  docusaurus/docs/snippets/createplugin-update.npm.shell.md
  docusaurus/docs/snippets/createplugin-update.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-update.yarn.shell.md
  docusaurus/docs/snippets/docker-grafana-version.npm.shell.md
  docusaurus/docs/snippets/docker-grafana-version.pnpm.shell.md
  docusaurus/docs/snippets/docker-grafana-version.yarn.shell.md
  docusaurus/docs/updating-to-new-releases.mdx
  docusaurus/website/docusaurus.config.js
  docusaurus/website/package.json
  docusaurus/website/src/components/CodeSnippets/CodeSnippets.tsx
  docusaurus/website/src/components/HomepageGettingStarted/index.tsx
  docusaurus/website/src/components/SyncCommand/SyncCommand.tsx
  docusaurus/website/src/pages/markdown-page.md
  docusaurus/website/src/theme/MDXComponents.tsx
  yarn.lock
Labels: documentation

#240 docs: readme update for windows
  packages/create-plugin/README.md
Labels: documentation

#243 create-plugin: documentation - add another webpack config example
  docusaurus/docs/advanced-configuration.md
Labels: documentation, create-plugin

#238 Create Plugin: Fix react types errors
  packages/create-plugin/templates/common/package.json
Labels: create-plugin, patch, release, chore

#244 Create Plugin: Update readme for supported package managers
  packages/create-plugin/README.md
Labels: documentation

#251 Fix fonts not loaded correctly on generated bundles
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, type/bug

#232 Chore: Update dev-dependencies
  packages/create-plugin/templates/common/package.json
Labels: dependencies, create-plugin, patch, release, chore

#242 create-plugin: updates for ci workflow
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
Labels: create-plugin, patch, release

#255 Docs: Add supported operating system section
  docusaurus/docs/getting-started.mdx
Labels: documentation

#257 Scripts: Add error-handling to generator scripts
  packages/create-plugin/scripts/generate-app-backend.js
  packages/create-plugin/scripts/generate-app.js
  packages/create-plugin/scripts/generate-datasource-with-backend.js
  packages/create-plugin/scripts/generate-datasource-without-backend.js
  packages/create-plugin/scripts/generate-panel.js
  packages/create-plugin/scripts/generate-scenes-app.js
Labels: type/bug

#256 Website: Add explanation for scenes app and link
  docusaurus/docs/creating-a-plugin.mdx
Labels: documentation

#259 CI: Use a GH app token
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
Labels: chore
