Repository grafana/plugin-tools, pull requests merged in 2023-06, with the labels that each got.

#260 Tooling: Use NX instead of Lerna for running tasks
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .github/workflows/test-build.yml
  nx.json
  package.json
  yarn.lock
Labels: enhancement, chore

#271 Create Plugin: Fix Code Coverage for JSX files
  packages/create-plugin/templates/common/.config/jest.config.js
Labels: create-plugin, patch, release, type/bug, pr/external

#266 Docs: Plugin-tools - Config and migration - chunk 7
  docusaurus/docs/advanced-configuration.md
  docusaurus/docs/migrating-from-toolkit.mdx
  docusaurus/docs/updating-to-new-releases.mdx
Labels: documentation, create-plugin

#269 Docs: Plugin-tools development material - chunk 8
  docusaurus/docs/backend.md
  docusaurus/docs/ci.md
  docusaurus/docs/docker.mdx
  docusaurus/docs/frontend.mdx
  docusaurus/docs/getting-started.mdx
  docusaurus/docs/nested-plugins.mdx
Labels: documentation

#258 Docs: Plugin-tools intro material - Doc review chunk 6
  docusaurus/docs/creating-a-plugin.mdx
  docusaurus/docs/folder-structure.md
  docusaurus/docs/getting-started.mdx
Labels: documentation

#274 Create Plugin: Enable apps by default
  packages/create-plugin/templates/app/provisioning/plugins/apps.yaml
  packages/create-plugin/templates/scenes-app/provisioning/plugins/apps.yaml
Labels: enhancement, create-plugin, minor, release

#263 Create Plugin: Introduce OS check
  packages/create-plugin/src/bin/run.ts
  packages/create-plugin/src/utils/utils.os.ts
Labels: enhancement, create-plugin, patch, release

#280 CI: Introduce Omit Commits
  .autorc
  package.json
  yarn.lock
Labels: no-changelog

#278 Chore: Migrate to NPM
  .github/workflows/ci.yml
  lerna.json
  package-lock.json
  package.json
  packages/create-plugin/package.json
  packages/sign-plugin/package.json
  yarn.lock
Labels: dependencies, create-plugin, sign-plugin, chore, no-changelog

#277 Docs: Fix snippets rendering after initial load
  docusaurus/docs/backend.md
  docusaurus/docs/creating-a-plugin.mdx
  docusaurus/docs/docker.mdx
  docusaurus/docs/getting-started.mdx
  docusaurus/docs/migrating-from-toolkit.mdx
  docusaurus/docs/nested-plugins.mdx
  docusaurus/docs/snippets/createplugin-install.npm.md
  docusaurus/docs/snippets/createplugin-install.pnpm.md
  docusaurus/docs/snippets/createplugin-install.yarn.md
  docusaurus/docs/snippets/createplugin-migrate.npm.md
  docusaurus/docs/snippets/createplugin-migrate.npm.shell.md
  docusaurus/docs/snippets/createplugin-migrate.pnpm.md
  docusaurus/docs/snippets/createplugin-migrate.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-migrate.yarn.md
  docusaurus/docs/snippets/createplugin-migrate.yarn.shell.md
  docusaurus/docs/snippets/createplugin-scaffold.npm.md
  docusaurus/docs/snippets/createplugin-scaffold.npm.shell.md
  docusaurus/docs/snippets/createplugin-scaffold.pnpm.md
  docusaurus/docs/snippets/createplugin-scaffold.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-scaffold.yarn.md
  docusaurus/docs/snippets/createplugin-scaffold.yarn.shell.md
  docusaurus/docs/snippets/createplugin-update.npm.md
  docusaurus/docs/snippets/createplugin-update.npm.shell.md
  docusaurus/docs/snippets/createplugin-update.pnpm.md
  docusaurus/docs/snippets/createplugin-update.pnpm.shell.md
  docusaurus/docs/snippets/createplugin-update.yarn.md
  docusaurus/docs/snippets/createplugin-update.yarn.shell.md
  docusaurus/docs/snippets/docker-grafana-version.npm.md
  docusaurus/docs/snippets/docker-grafana-version.npm.shell.md
  docusaurus/docs/snippets/docker-grafana-version.pnpm.md
  docusaurus/docs/snippets/docker-grafana-version.pnpm.shell.md
  docusaurus/docs/snippets/docker-grafana-version.yarn.md
  docusaurus/docs/snippets/docker-grafana-version.yarn.shell.md
  docusaurus/docs/updating-to-new-releases.mdx
  docusaurus/website/docusaurus.config.js
  docusaurus/website/globals.d.ts
  docusaurus/website/plugins/docusaurus-custom-webpack-plugin.js
  docusaurus/website/src/components/CodeSnippets/CodeSnippets.tsx
  docusaurus/website/src/components/HomepageFeatures/index.tsx
  docusaurus/website/src/components/HomepageGettingStarted/index.tsx
  docusaurus/website/src/components/SyncCommand/SyncCommand.tsx
Labels: documentation, no-changelog

#282 CI: Fix website deploy script
  .github/workflows/deploy.yml
  .github/workflows/test-build.yml
Labels: documentation, chore, no-changelog

#279 Create Plugin: Bump dependencies
  packages/create-plugin/src/constants.ts
  packages/create-plugin/templates/common/package.json
Labels: create-plugin, patch, release, chore

#286 Making grafana-image parameter flexible
  docusaurus/docs/docker.mdx
  packages/create-plugin/src/constants.ts
  packages/create-plugin/templates/common/docker-compose.yaml
Labels: documentation, create-plugin, minor
