Repository grafana/plugin-tools, pull requests merged in 2024-06, with the labels that each got.

#941 Plugin E2E: Fix - skip creating user if it's the default server admin
  packages/create-plugin/templates/common/_package.json
  packages/plugin-e2e/src/auth/auth.setup.ts
Labels: patch, release, type/bug

#944 Plugin E2E: Fix menuitemclick in Grafana <=9.1.0
  .github/workflows/playwright.yml
  packages/plugin-e2e/src/models/components/Panel.ts
Labels: patch, release

#946 Create Plugin: Remove meta-extractor from package.json
  packages/create-plugin/templates/common/_package.json
Labels: create-plugin, patch, release

#824 Docs: Add resource handler topic
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-resource-handler.md
Labels: type/docs, no-changelog

#779 Plugin E2E: Add support for testing alert query
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/alert-queries.md
  packages/plugin-e2e/provisioning/alerting/alerts.yml
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
  packages/plugin-e2e/src/fixtures/alertRuleEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAlertRuleEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/readProvisionedAlertRule.ts
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/models/components/AlertRuleQuery.ts
  packages/plugin-e2e/src/models/components/DataSourcePicker.ts
  packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.spec.ts
Labels: minor, release

#948 Chore: Remove need to patch packages and clean up package-lock.json
  .gitignore
  package-lock.json
  package.json
  patches/@types+marked-terminal+6.0.1.patch
Labels: dependencies, chore, no-changelog

#942 Plugin E2E: Expose variable list page as fixture
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-resource-handler.md
  docusaurus/docs/tutorials/convert-a-frontend-datasource-to-backend.md
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
  packages/plugin-e2e/src/fixtures/commands/gotoVariablePage.ts
  packages/plugin-e2e/src/fixtures/variablePage.ts
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/models/pages/ExplorePage.ts
  packages/plugin-e2e/src/models/pages/VariablePage.ts
  packages/plugin-e2e/src/types.ts
Labels: minor, release

#953 Create Plugin: Support WASM in plugin builds
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: minor, release

#955 Docs: Plugin E2E - Remove no longer relevant text
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
Labels: no-changelog

#956 Docs: Plugin E2E - Fix typos
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
Labels: no-changelog

#926 Docs: Rename/move 'introduction' to 'key concepts' and fix broken links
  .github/workflows/test-build.yml
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/panel-properties.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-backend.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/work-with-data-frames.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-authentication-for-data-source-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-logs-metrics-traces-for-backend-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-resource-handler.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/index.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-panel-plugin.md
  docusaurus/docs/e2e-test-a-plugin/test-an-app-plugin/configuration-editor.md
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/introduction/_category_.json
  docusaurus/docs/introduction/index.md
  docusaurus/docs/key-concepts/_category_.json
  docusaurus/docs/key-concepts/backend-plugins/_category_.json
  docusaurus/docs/key-concepts/backend-plugins/grafana-plugin-sdk-for-go.md
  docusaurus/docs/key-concepts/backend-plugins/index.md
  docusaurus/docs/key-concepts/backend-plugins/plugin-protocol.md
  docusaurus/docs/key-concepts/data-frames.md
  docusaurus/docs/key-concepts/index.md
  docusaurus/docs/key-concepts/manage-npm-dependencies.md
  docusaurus/docs/key-concepts/plugin-lifecycle.md
  docusaurus/docs/key-concepts/plugin-types-usage.md
  docusaurus/docs/key-concepts/ui-extensions.md
  docusaurus/docs/migration-guides/angular-react/angular-react-convert-from-time_series2.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v6.x-v7.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
  docusaurus/docs/plugin-examples/index.md
  docusaurus/docs/reference/prompts.md
  docusaurus/docs/tutorials/_category_.json
  docusaurus/docs/tutorials/build-a-data-source-backend-plugin.md
  docusaurus/docs/tutorials/build-a-data-source-plugin.md
  docusaurus/docs/tutorials/build-a-panel-plugin.md
  docusaurus/docs/tutorials/convert-a-frontend-datasource-to-backend.md
  docusaurus/docs/ui-extensions/index.md
  docusaurus/website/docusaurus.config.base.js
  packages/create-plugin/templates/_partials/backend-getting-started.md
  packages/plugin-e2e/src/models/pages/GrafanaPage.ts
Labels: type/docs, no-changelog

#872 README: Update package list
  README.md
Labels: type/docs, chore, no-changelog

#967 Chore: Update WS npm package
  package-lock.json
Labels: dependencies, chore, javascript, no-changelog

#965 Plugin E2E: Interact with Grafana http api on behalf of logged in user
  packages/plugin-e2e/src/auth/auth.setup.ts
  packages/plugin-e2e/src/fixtures/commands/createUser.ts
  packages/plugin-e2e/src/fixtures/commands/gotoDataSourceConfigPage.ts
  packages/plugin-e2e/src/fixtures/commands/login.ts
  packages/plugin-e2e/src/fixtures/grafanaAPIClient.ts
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/models/GrafanaAPIClient.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/permissions/createUserUsingInvalidCredentials.spec.ts
  packages/plugin-e2e/tests/as-admin-user/permissions/createUserUsingValidCredentials.spec.ts
  packages/plugin-e2e/tests/as-viewer-user/permissions/createUserUsingInvalidCredentials.spec.ts
  packages/plugin-e2e/tests/as-viewer-user/permissions/createUserUsingValidCredentials.spec.ts
Labels: minor, release

#914 Docs: New App plugin tutorial
  docusaurus/docs/create-a-plugin/extend-a-plugin/nested-plugins.md
  docusaurus/docs/create-a-plugin/extend-a-plugin/nested-plugins.mdx
  docusaurus/docs/tutorials/build-an-app-plugin.md
Labels: type/docs, no-changelog

#954 Docs: Update reference for the extensions
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
  docusaurus/docs/how-to-guides/_category_.json
  docusaurus/docs/how-to-guides/ui-extensions/_category_.json
  docusaurus/docs/how-to-guides/ui-extensions/create-an-extension-point.md
  docusaurus/docs/how-to-guides/ui-extensions/expose-a-component.md
  docusaurus/docs/how-to-guides/ui-extensions/register-an-extension.md
  docusaurus/docs/how-to-guides/ui-extensions/use-an-exposed-component.md
  docusaurus/docs/key-concepts/plugin-types-usage.md
  docusaurus/docs/key-concepts/ui-extensions.md
  docusaurus/docs/reference/ui-extensions.md
  docusaurus/docs/shared/extension-points.md
  docusaurus/docs/ui-extensions/create-an-extension-point.md
  docusaurus/docs/ui-extensions/index.md
  docusaurus/docs/ui-extensions/register-an-extension.md
  docusaurus/website/docusaurus.config.base.js
Labels: type/docs, no-changelog

#974 Create Plugin: Use caret range for plugin-e2e
  packages/create-plugin/templates/common/_package.json
Labels: no-changelog

#975 Renovate: Disable dependency dashboards
  .github/renovate.json
Labels: no-changelog
