Repository grafana/plugin-tools, pull requests merged in 2024-12, with the labels that each got.

#1355 chore(deps): update dependency cross-spawn to v7.0.6
  package-lock.json
Labels: dependencies, javascript, no-changelog

#1367 Update get-started.mdx
  docusaurus/docs/get-started/get-started.mdx
Labels: type/docs, no-changelog

#1363 Document user storage
  docusaurus/docs/how-to-guides/add-user-storage.md
Labels: no-changelog, documentation

#1357 Create Plugin: Add bundle stats workflow
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/github/workflows/bundle-stats.yml
  packages/create-plugin/templates/github/workflows/ci.yml
Labels: create-plugin, minor, release

#1390 Dependencies: Use latest release of plugin-e2e
  packages/create-plugin/templates/common/_package.json
Labels: patch, release

#1391 Plugin E2E: Fix some APIs that were broken in older versions of Grafana
  .github/workflows/playwright.yml
  .gitignore
  package-lock.json
  packages/plugin-e2e/package.json
  packages/plugin-e2e/src/models/components/Panel.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/src/selectors/versionedAPIs.ts
  playwright/.auth/admin.json
  playwright/.auth/grafanaAPICredentials.json
Labels: patch, release

#1392 Docs: Add note about paid plugins to homepage
  docusaurus/docs/get-started/get-started.mdx
Labels: type/docs, no-changelog

#1369 Create-plugin): Remove unused dependencies according to Knip report
  .github/knip.json
  packages/create-plugin/templates/app/src/components/AppConfig/AppConfig.tsx
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/github/workflows/is-compatible.yml
  packages/create-plugin/templates/scenes-app/src/components/AppConfig/AppConfig.tsx
  packages/create-plugin/templates/scenes-app/src/pages/Home/CustomSceneObject.tsx
Labels: create-plugin, minor, chore

#1379 Docs: Clarify info on converting dataframes from long to wide
  docusaurus/docs/key-concepts/data-frames.md
Labels: type/docs, no-changelog

#1399 Chore: Switching to main
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/github/workflows/release.yml
Labels: create-plugin, minor

#1393 Docs: Add prominent page for resources and support
  docusaurus/docs/resources.md
Labels: type/docs, no-changelog

#1411 Chore: Stop eslint peer dependency warnings on npm install
  package-lock.json
  package.json
Labels: chore, no-changelog

#1410 Docs: Update references to Grafana 11
  docusaurus/docs/e2e-test-a-plugin/migrate-from-grafana-e2e.md
  docusaurus/docs/key-concepts/data-frames.md
Labels: no-changelog, documentation

#1331 Website: Speed up builds with docusaurus/faster
  docusaurus/website/docusaurus.config.base.ts
  docusaurus/website/package.json
  package-lock.json
Labels: type/docs, no-changelog

#1418 Create Plugin: Change scaffolded tests
  .github/workflows/ci.yml
  packages/create-plugin/templates/backend/tests/configEditor.spec.ts
  packages/create-plugin/templates/backend/tests/queryEditor.spec.ts
  packages/create-plugin/templates/common/.config/Dockerfile
  packages/create-plugin/templates/common/docker-compose.yaml
  packages/create-plugin/templates/datasource/tests/configEditor.spec.ts
  packages/create-plugin/templates/datasource/tests/queryEditor.spec.ts
  packages/create-plugin/templates/github/workflows/ci.yml
Labels: no-changelog

#1421 Create Plugin: Fix scaffolded panel plugin tests
  packages/create-plugin/templates/panel/tests/panel.spec.ts
Labels: patch, release, type/bug

#1425 Create Plugin: Fix incorrect interpolation for anonymous auth variable
  packages/create-plugin/templates/common/.config/Dockerfile
Labels: patch, release, type/bug

#1426 Create Plugin: Fix cache busting chunks using contenthash
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, patch, release

#1424 chore: align nvmrc node with package.json
  packages/create-plugin/templates/common/.nvmrc
Labels: patch

#1384 Create Plugin: Use `module.tsx` in is-compatible workflow for apps
  packages/create-plugin/templates/github/workflows/is-compatible.yml
Labels: create-plugin, patch, release, type/bug
