Repository grafana/plugin-tools, pull requests merged in 2024-01, with the labels that each got.

#616 Plugin E2E: Enable testing panel plugins
  .github/workflows/playwright.yml
  packages/plugin-e2e/docker-compose.yaml
  packages/plugin-e2e/provisioning/dashboards/clock-panel.json
  packages/plugin-e2e/src/e2e-selectors/resolver.test.ts
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/tests/datasource/configEditor.spec.ts
  packages/plugin-e2e/tests/panel/panel.spec.ts
  packages/plugin-e2e/tests/utils.ts
Labels: minor, release

#633 Plugin E2E: Tidy up changelog
  packages/plugin-e2e/CHANGELOG.md
Labels: no-changelog

#635 Fix broken link in best practices
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
Labels: no-changelog

#636 CI: Conditionally build docs
  .github/workflows/test-build.yml
Labels: no-changelog

#640 Plugin E2E: Comment public apis
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/matchers/toDisplayPreviews.ts
  packages/plugin-e2e/src/models/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/AnnotationPage.ts
  packages/plugin-e2e/src/models/DashboardPage.ts
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
  packages/plugin-e2e/src/models/DataSourcePicker.ts
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/models/TimeRange.ts
  packages/plugin-e2e/src/models/VariableEditPage.ts
  packages/plugin-e2e/src/models/VariablePage.ts
  packages/plugin-e2e/src/types.ts
Labels: minor, release

#641 Plugin E2E: Tidy up selectors
  packages/plugin-e2e/src/e2e-selectors/resolver.test.ts
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/README.md
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
Labels: minor, release

#642 Github workflows: Add correct permissions to the release workflow
  packages/create-plugin/templates/github/ci/.github/workflows/release.yml
Labels: create-plugin, patch, release, type/bug

#644 Plugin E2E: Re-adding a few selectors
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
Labels: patch, release

#649 Plugin E2E: Bump playwright to latest version
  package-lock.json
  packages/plugin-e2e/package.json
Labels: minor, release

#634 Plugin E2E: Add contributing guidelines
  packages/plugin-e2e/CONTRIBUTING.md
  packages/plugin-e2e/README.md
  packages/plugin-e2e/package.json
Labels: minor, release

#650 Plugin E2E: Restructure tests folder
  packages/plugin-e2e/tests/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/datasource/feature-toggles/queryDataHandler.spec.ts
  packages/plugin-e2e/tests/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/datasource/query-editor/queryEditor.spec.ts
  packages/plugin-e2e/tests/selectors.spec.ts
Labels: no-changelog

#647 Only run ts checker and eslint plugins in webpack dev mode
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, patch, release

#653 Plugin E2E: Apply docs pr feedback
  packages/plugin-e2e/CONTRIBUTING.md
Labels: no-changelog

#624 Fix eslint not generating in plugin migrations
  packages/create-plugin/src/commands/migrate.command.ts
  packages/create-plugin/src/utils/utils.files.ts
Labels: create-plugin, patch, release

#657 Chore: Fixed liniting issues in template
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
  packages/create-plugin/templates/common/docker-compose.yaml
Labels: patch, type/bug

#658 Build: Migrate create-plugin to ESM
  .github/workflows/ci.yml
  package-lock.json
  package.json
  packages/create-plugin/package.json
  packages/create-plugin/src/bin/run.ts
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/generate/prettify-files.ts
  packages/create-plugin/src/commands/generate/print-success-message.ts
  packages/create-plugin/src/commands/generate/prompt-user.ts
  packages/create-plugin/src/commands/generate/update-go-sdk-and-packages.ts
  packages/create-plugin/src/commands/index.ts
  packages/create-plugin/src/commands/migrate.command.ts
  packages/create-plugin/src/commands/provisioning.command.ts
  packages/create-plugin/src/commands/types.ts
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/commands/version.command.ts
  packages/create-plugin/src/constants.ts
  packages/create-plugin/src/utils/tests/utils.files.test.ts
  packages/create-plugin/src/utils/tests/utils.handlebars.test.ts
  packages/create-plugin/src/utils/tests/utils.npm.test.ts
  packages/create-plugin/src/utils/tests/utils.plugin.test.ts
  packages/create-plugin/src/utils/tests/utils.templates.test.ts
  packages/create-plugin/src/utils/utils.config.ts
  packages/create-plugin/src/utils/utils.console.ts
  packages/create-plugin/src/utils/utils.files.ts
  packages/create-plugin/src/utils/utils.handlebars.ts
  packages/create-plugin/src/utils/utils.npm.ts
  packages/create-plugin/src/utils/utils.packageManager.ts
  packages/create-plugin/src/utils/utils.packagejson.ts
  packages/create-plugin/src/utils/utils.path.ts
  packages/create-plugin/src/utils/utils.plugin.ts
  packages/create-plugin/src/utils/utils.templates.ts
  packages/create-plugin/src/utils/utils.version.ts
  packages/create-plugin/tsconfig.json
  packages/create-plugin/vitest.config.ts
  patches/@types+marked-terminal+6.0.1.patch
  tsconfig.base.json
Labels: major, release, chore

#621 Revert "Revert "Chore: Bump Auto npm packages to ^11.x.x""
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: chore, no-changelog

#571 Docs: IAM plugin json field
  docusaurus/docs/metadata.md
Labels: type/docs, no-changelog

#660 Use `custom.ini` file provided to configure Grafana docker container
  packages/create-plugin/templates/scenes-app/provisioning/custom.ini
Labels: minor, release

#670 Plugin E2E: Use node16
  packages/plugin-e2e/README.md
  packages/plugin-e2e/package.json
  packages/plugin-e2e/tsconfig.json
Labels: minor, release

#662 Build: Migrate sign-plugin to ESM
  package-lock.json
  packages/sign-plugin/jest.config.js
  packages/sign-plugin/package.json
  packages/sign-plugin/src/bin/run.ts
  packages/sign-plugin/src/commands/index.ts
  packages/sign-plugin/src/commands/sign.command.ts
  packages/sign-plugin/src/commands/version.command.ts
  packages/sign-plugin/src/utils/getVersion.ts
  packages/sign-plugin/src/utils/manifest.ts
  packages/sign-plugin/src/utils/pluginValidation.test.ts
  packages/sign-plugin/src/utils/request.ts
  packages/sign-plugin/tsconfig.json
  packages/sign-plugin/vitest.config.ts
Labels: sign-plugin, major, release, chore

#672 Plugin E2E: Update changed selector
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
Labels: patch, release

#671 Docs: Fix typo in extend-a-plugin overview page
  docusaurus/docs/create-a-plugin/extend-a-plugin/index.md
Labels: type/docs, no-changelog

#673 CI: Set publishing to dry-run and verbose for debugging
  package.json
Labels: chore, no-changelog

#652 Create Plugin: Update outdated plop related packages to latest
  package-lock.json
  packages/create-plugin/jest.config.js
  packages/create-plugin/package.json
  packages/create-plugin/src/utils/utils.handlebars.ts
Labels: create-plugin, patch, release

#665 Docs: Add "we don't support" note
  docusaurus/docs/introduction/plugin-types-usage.md
Labels: type/docs, no-changelog

#676 CI: Fix Auto passing --registry arg to Lerna in dry-run
  package.json
Labels: chore, no-changelog

#675 Release: Put back plugin-e2e 0.9.0 and cleanup changelogs
  CHANGELOG.md
  CONTRIBUTING.md
  packages/plugin-e2e/CHANGELOG.md
  packages/plugin-e2e/package.json
Labels: type/docs, no-changelog

#678 CI: Enable NPM publishing
  package.json
Labels: chore, no-changelog

#681 Chore: Rollback Auto to 11.0.2 due to potential publishing bug
  package-lock.json
  package.json
Labels: chore, no-changelog

#677 Plugin E2E: Fix typo
  packages/plugin-e2e/src/models/PanelEditPage.ts
Labels: no-changelog

#651 Plugin E2E: Change FE feature toggles during test session
  packages/plugin-e2e/playwright.config.ts
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/fixtures/page.ts
  packages/plugin-e2e/src/fixtures/scripts/overrideFeatureToggles.js
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/datasource/feature-toggles/queryDataHandler.spec.ts
  packages/plugin-e2e/tests/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/datasource/feature-toggles/queryEditor.sync.spec.ts
  packages/plugin-e2e/tsconfig.json
Labels: minor, release

#689 CI: Rollback Auto to 11.0.1 to fix gh release publishing
  package-lock.json
  package.json
Labels: chore, no-changelog

#691 Plugin E2E: Fix isFeatureEnabled fixture
  packages/plugin-e2e/src/fixtures/isFeatureToggleEnabled.ts
  packages/plugin-e2e/src/fixtures/page.ts
  packages/plugin-e2e/src/fixtures/scripts/overrideFeatureToggles.js
  packages/plugin-e2e/tests/datasource/feature-toggles/queryEditor.async.spec.ts
Labels: patch, release

#645 Plugin E2E: Publish report to cloud storage
  .github/workflows/playwright.yml
Labels: no-changelog

#692 Plugin E2E: Add new version for selector
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
Labels: patch, release

#685 docs: add migration valuemaps
  docusaurus/docs/migration-guides/angular-react/convert-value-and-range-maps.md
Labels: type/docs, no-changelog

#663 add plugin build automation doc
  docusaurus/docs/publish-a-plugin/build-automation.md
Labels: type/docs, no-changelog

#695 CI: Test scaffolds against built NPM packages
  .github/workflows/ci.yml
  .gitignore
Labels: create-plugin, sign-plugin, chore, no-changelog

#686 Suggest using semver for plugin versioning in plugin.json
  docusaurus/docs/metadata.md
Labels: type/docs, no-changelog

#697 Update headings in build-a-logs-data-source-plugin.md
  docusaurus/docs/tutorials/build-a-logs-data-source-plugin.md
Labels: type/docs, no-changelog

#682 create-plugin: adds archive option for CI workflow
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
Labels: enhancement, create-plugin, patch

#700 Plugin E2E: Add auth test file
  packages/plugin-e2e/src/auth/auth.setup.ts
Labels: patch, release

#698 Plugin E2E: Decouple panel from pages
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/matchers/index.ts
  packages/plugin-e2e/src/matchers/toHavePanelError.ts
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/GrafanaPage.ts
  packages/plugin-e2e/src/models/Panel.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/datasource/query-editor/queryEditor.integration.spec.ts
Labels: minor, release

#699 Plugin E2E: Make getQueryEditorRow method sync
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/tests/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/datasource/explore/queryEditor.spec.ts
  packages/plugin-e2e/tests/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/datasource/query-editor/queryEditor.spec.ts
Labels: patch, release
