Repository grafana/plugin-tools, pull requests merged in 2024-11, with the labels that each got.

#1281 Create Plugin: Add `buildMode` property to plugin.json asset
  packages/create-plugin/templates/common/.config/webpack/BuildModeWebpackPlugin.ts
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: minor, release

#1279 Renovate: Restrict selector updates to only plugin-e2e package
  .github/renovate.json5
Labels: no-changelog

#1293 Renovate: Add release label to e2e-selector updates in the plugin-e2e package
  .github/renovate.json5
Labels: no-changelog

#1302 chore: add docker login step to playwright workflow
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
Labels: no-changelog

#1213 Docs: Add documentation about setMigrationHandler for panels
  docusaurus/docs/how-to-guides/panel-plugins/options-migration-handler.md
Labels: type/docs, no-changelog, documentation

#1308 Chore: Update package.json files to prevent lock file changes in dev
  docusaurus/website/package.json
  packages/plugin-e2e/package.json
Labels: no-changelog

#1306 Create plugin: Remove console.log from webpack buildmode plugin
  packages/create-plugin/templates/common/.config/webpack/BuildModeWebpackPlugin.ts
Labels: patch

#1282 ref: set testdata-db DS for panel plugin
  docusaurus/docs/tutorials/build-a-panel-plugin.md
  packages/create-plugin/templates/panel/provisioning/dashboards/dashboard.json
Labels: minor

#1274 Docs: Update plugin-e2e contributing guidelines
  packages/plugin-e2e/CONTRIBUTING.md
Labels: no-changelog

#1307 Create Plugin: Add plugin.json check step to CI
  packages/create-plugin/templates/github/workflows/ci.yml
Labels: create-plugin, minor

#1298 Support node 22
  .github/workflows/check-labels.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-to-developer-portal-dev.yml
  .github/workflows/deploy-to-developer-portal-prod.yml
  .github/workflows/playwright.yml
  .github/workflows/test-build.yml
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/github/workflows/ci.yml
  packages/create-plugin/templates/github/workflows/is-compatible.yml
  packages/plugin-e2e/package.json
Labels: dependencies, minor, release

#1319 Create Plugin: Fix failing scaffolds due to marked
  package-lock.json
  packages/create-plugin/package.json
Labels: create-plugin, patch, release

#1323 Create Plugin: Add error-handling for JSON parsing in utils
  packages/create-plugin/src/utils/utils.goSdk.ts
Labels: create-plugin, patch, release, type/bug

#1325 Revert "chore(deps): update dependency cookie to v1"
  package-lock.json
  package.json
Labels: type/docs, no-changelog

#1330 Create plugin: Fix plugin.json check step on CI
  packages/create-plugin/templates/github/workflows/ci.yml
Labels: create-plugin, patch, release

#1332 Chore: Add plugin.json check to CI
  .github/workflows/ci.yml
Labels: no-changelog

#1342 Docs: Update DataSourceWithSupplementaryQueriesSupport instructions
  docusaurus/docs/tutorials/build-a-logs-data-source-plugin.md
Labels: patch, documentation

#1329 Docs: Add smoke test examples to datasource guides
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/custom-variable-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
Labels: no-changelog

#1334 E2E Workflow: Schedule e2e workflow to run once per day
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.yarn.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.yarn.md
Labels: no-changelog

#1360 CI: Add Knip to understand dependency usage
  .github/knip.json
  .github/workflows/ci.yml
Labels: no-changelog, ci
