Repository grafana/plugin-tools, pull requests merged in 2024-03, with the labels that each got.

#766 Docs: Plugin E2E - Custom variable editor article
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/custom-variable-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  docusaurus/website/static/img/variable-preview.png
Labels: no-changelog

#798 Docs: Plugin E2E - Add annotations article
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/custom-variable-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  packages/plugin-e2e/src/index.ts
Labels: no-changelog

#804 Docs: 2nd editorial pass on several E2E testing topics
  docusaurus/docs/e2e-test-a-plugin/ci.md
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/introduction.md
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
Labels: type/docs, no-changelog

#806 Plugin E2E: Workflow fixes
  .github/workflows/playwright.yml
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.yarn.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.yarn.md
Labels: no-changelog

#807 Edit 3 e2e files
  docusaurus/docs/e2e-test-a-plugin/authentication.md
  docusaurus/docs/e2e-test-a-plugin/feature-toggles.md
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
Labels: type/docs, no-changelog

#808 Docs: Plugin E2E - Guide on how to select elements
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
Labels: no-changelog

#810 Plugin E2E: Add QueryField container selector
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
Labels: patch, release

#769 Plugin E2E: Pass testinfo to models
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
  packages/plugin-e2e/src/fixtures/annotationEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSourceConfigPage.ts
  packages/plugin-e2e/src/fixtures/explorePage.ts
  packages/plugin-e2e/src/fixtures/newDashboardPage.ts
  packages/plugin-e2e/src/fixtures/variableEditPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/variableInterpolation.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panel.spec.ts
Labels: minor, release

#812 Plugin E2E: Make it easier to navigate to existing resources
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/custom-variable-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  packages/plugin-e2e/provisioning/datasources/google-sheets-datasource-jwt.yaml
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAnnotationEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAppConfigPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoDashboardPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoDataSourceConfigPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoPanelEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoVariableEditPage.ts
  packages/plugin-e2e/src/fixtures/dashboardPage.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/fixtures/newDashboardPage.ts
  packages/plugin-e2e/src/fixtures/panelEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panel.spec.ts
Labels: minor, release

#815 Docs: Plugin E2E - Fix typos
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
Labels: no-changelog

#811 migration guide: "Targeting “older” grafana releases - v7.x or v8.0.7 vs 8.4.x (or whatever is latest)
  docusaurus/docs/migration-guides/angular-react/targeting-older-releases.md
Labels: type/docs, no-changelog

#799 Docs: Add ReturnToPrevious documentation
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-return-to-previous-functionality.md
Labels: type/docs, no-changelog

#819 fix: respect package manager in update next steps
  packages/create-plugin/src/commands/update.command.ts
Labels: create-plugin, patch, release, type/bug

#813 Docs: Removing migration doc for 10.x > 11.x that mentions vector removal
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.x-v11.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md
Labels: type/docs, chore, no-changelog, skip-release

#817 Chore: Added missing nodemon config to plugin-e2e
  packages/plugin-e2e/package.json
Labels: chore, no-changelog

#822 Create Plugin: upgrade @grafana/eslint-config to 7.0.0
  packages/create-plugin/templates/common/_package.json
Labels: create-plugin, patch, release

#821 E2E: Added command and page to interact with app pages
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAppPage.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/models/index.ts
  packages/plugin-e2e/src/models/pages/AppConfigPage.ts
  packages/plugin-e2e/src/models/pages/AppPage.ts
  packages/plugin-e2e/src/models/pages/PluginConfigPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/app/app-page/app-page.spec.ts
  packages/plugin-e2e/tests/as-admin-user/app/app-page/goto-app-page.spec.ts
Labels: minor, release

#823 Create Plugin: Remove devOnly parameter and related test cases
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/utils/tests/utils.npm.test.ts
  packages/create-plugin/src/utils/utils.npm.ts
Labels: create-plugin, patch, release

#830 Add condition about backend to success message
  packages/create-plugin/src/commands/generate/print-success-message.ts
Labels: create-plugin, patch

#816 New Doc: Adding a suggestion supplier to a plugin
  docusaurus/docs/migration-guides/angular-react/suggestion-supplier.md
Labels: type/docs, no-changelog

#831 Docs: Clarify some points in documentation and typedocs
  docusaurus/docs/e2e-test-a-plugin/authentication.md
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/introduction.md
  packages/plugin-e2e/src/types.ts
Labels: type/docs, no-changelog

#809 Create Plugin: add support for remote debugging in docker dev env
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/common/.config/Dockerfile
  packages/create-plugin/templates/common/.config/entrypoint.sh
  packages/create-plugin/templates/common/.config/supervisord/supervisord.conf
  packages/create-plugin/templates/common/docker-compose.yaml
Labels: create-plugin, minor, release

#833 Plugin E2E: Use new e2e selectors
  .gitignore
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/models/components/TimeRange.ts
  packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/pages/AnnotationPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
Labels: minor, release

#836 Create plugin: Update data source templates
  docusaurus/docs/tutorials/build-a-streaming-data-source-plugin.md
  packages/create-plugin/templates/backend/src/datasource.ts
  packages/create-plugin/templates/datasource/src/components/ConfigEditor.tsx
  packages/create-plugin/templates/datasource/src/components/QueryEditor.tsx
  packages/create-plugin/templates/datasource/src/datasource.ts
Labels: patch, release

#838 Plugin E2E: Change package imports and exports
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/auth/auth.setup.ts
  packages/plugin-e2e/src/fixtures/annotationEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSource.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSourceConfigPage.ts
  packages/plugin-e2e/src/fixtures/commands/createUser.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAnnotationEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAppConfigPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoAppPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoDashboardPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoDataSourceConfigPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoPanelEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/gotoVariableEditPage.ts
  packages/plugin-e2e/src/fixtures/commands/login.ts
  packages/plugin-e2e/src/fixtures/commands/readProvisionedDashboard.ts
  packages/plugin-e2e/src/fixtures/commands/readProvisionedDataSource.ts
  packages/plugin-e2e/src/fixtures/dashboardPage.ts
  packages/plugin-e2e/src/fixtures/explorePage.ts
  packages/plugin-e2e/src/fixtures/grafanaVersion.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/fixtures/isFeatureToggleEnabled.ts
  packages/plugin-e2e/src/fixtures/page.ts
  packages/plugin-e2e/src/fixtures/panelEditPage.ts
  packages/plugin-e2e/src/fixtures/selectors.ts
  packages/plugin-e2e/src/fixtures/types.ts
  packages/plugin-e2e/src/fixtures/variableEditPage.ts
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/matchers/index.ts
  packages/plugin-e2e/src/matchers/toBeOK.ts
  packages/plugin-e2e/src/matchers/toDisplayPreviews.ts
  packages/plugin-e2e/src/matchers/toHaveAlert.ts
  packages/plugin-e2e/src/models/index.ts
  packages/plugin-e2e/src/models/pages/AppPage.ts
  packages/plugin-e2e/src/options.ts
  packages/plugin-e2e/src/types.ts
Labels: minor, release

#840 Plugin E2E: Remove publish-report step from workflow
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.yarn.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.yarn.md
Labels: no-changelog

#842 Docs: Fix Saga link
  docusaurus/docs/create-a-plugin/develop-a-plugin/best-practices.md
Labels: type/docs, no-changelog

#843 Create-Plugin: Improve commands intructions
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/src/commands/generate/print-success-message.ts
Labels: patch, release

#844 Create Plugin: Fix grafana running without plugin backend
  packages/create-plugin/templates/common/.config/supervisord/supervisord.conf
Labels: patch, release

#839 Create Plugin: Update default yarn version to 1.22.22
  packages/create-plugin/src/utils/utils.packageManager.ts
Labels: create-plugin, patch, release, chore

#846 Create Plugin: Fix hardcoded path
  packages/create-plugin/templates/common/.config/supervisord/supervisord.conf
Labels: patch, release
