Repository grafana/plugin-tools, pull requests merged in 2024-04, with the labels that each got.

#849 Docs: G11 migration guide
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.x-v11.x.md
Labels: no-changelog

#832 Plugin E2E: Rename getByTestIdOrAriaLabel to getByGrafanaSelector
  docusaurus/docs/e2e-test-a-plugin/feature-toggles.md
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/custom-variable-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  packages/plugin-e2e/CONTRIBUTING.md
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/matchers/toDisplayPreviews.ts
  packages/plugin-e2e/src/matchers/toHaveAlert.ts
  packages/plugin-e2e/src/models/components/DataSourcePicker.ts
  packages/plugin-e2e/src/models/components/Panel.ts
  packages/plugin-e2e/src/models/components/TimeRange.ts
  packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/pages/AnnotationPage.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/src/models/pages/DataSourceConfigPage.ts
  packages/plugin-e2e/src/models/pages/ExplorePage.ts
  packages/plugin-e2e/src/models/pages/GrafanaPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/src/models/pages/VariableEditPage.ts
  packages/plugin-e2e/src/models/pages/VariablePage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.sync.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
Labels: minor, release

#739 Plugin E2E: Fix APIs that are broken in older versions of Grafana
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  packages/create-plugin/src/commands/generate/print-success-message.ts
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
  packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/pages/ExplorePage.ts
  packages/plugin-e2e/src/models/pages/VariableEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
Labels: patch, release

#853 Plugin-E2E: Allow setting custom visualization
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
Labels: minor, release

#857 Create Plugins: Add feature to toggle docker development environment
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/common/.config/Dockerfile
  packages/create-plugin/templates/common/.config/entrypoint.sh
Labels: create-plugin, minor, release

#693 Angular Migration: conversion from time_series2
  docusaurus/docs/migration-guides/angular-react/angular-react-convert-from-time_series2.md
Labels: type/docs, no-changelog

#684 docs: migrating angular custom configuration editors to react components
  docusaurus/docs/migration-guides/angular-react/angular-react-custom-configuration-components.md
  docusaurus/website/static/img/migration-screenshots/composite-component-react-expanded.png
  docusaurus/website/static/img/migration-screenshots/composite-editor-angular-expanded.png
  docusaurus/website/static/img/migration-screenshots/composite-editor-angular.png
  docusaurus/website/static/img/migration-screenshots/composite-react-component-add-metric.png
  docusaurus/website/static/img/migration-screenshots/composite-react-component.png
Labels: type/docs, no-changelog

#859 Plugin E2E: Remove custom selector engine
  packages/plugin-e2e/README.md
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/src/selectorEngine.ts
  packages/plugin-e2e/src/types.ts
Labels: major, release

#861 Docs: Add entry for plugin-e2e v1.0.0 in changelogs
  CHANGELOG.md
  packages/plugin-e2e/CHANGELOG.md
Labels: type/docs, no-changelog

#860 Plugin E2E: Add plugin options in readme snippet
  packages/plugin-e2e/README.md
Labels: patch, release

#847 Create Plugin: Scaffold plugins with playwright for e2e
  .github/workflows/ci.yml
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/generate/print-success-message.ts
  packages/create-plugin/src/constants.ts
  packages/create-plugin/src/types.ts
  packages/create-plugin/src/utils/tests/utils.handlebars.test.ts
  packages/create-plugin/src/utils/tests/utils.templates.test.ts
  packages/create-plugin/src/utils/utils.config.ts
  packages/create-plugin/src/utils/utils.files.ts
  packages/create-plugin/src/utils/utils.handlebars.ts
  packages/create-plugin/src/utils/utils.templates.ts
  packages/create-plugin/templates/app/src/components/AppConfig/AppConfig.tsx
  packages/create-plugin/templates/app/tests/appConfig.spec.ts
  packages/create-plugin/templates/app/tests/appNavigation.spec.ts
  packages/create-plugin/templates/app/tests/fixtures.ts
  packages/create-plugin/templates/backend/pkg/models/settings.go
  packages/create-plugin/templates/backend/pkg/plugin/datasource.go
  packages/create-plugin/templates/backend/tests/configEditor.spec.ts
  packages/create-plugin/templates/backend/tests/queryEditor.spec.ts
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/common/cypress.json
  packages/create-plugin/templates/common/cypress/integration/01-smoke.spec.ts
  packages/create-plugin/templates/common/gitignore
  packages/create-plugin/templates/common/npmrc
  packages/create-plugin/templates/common/playwright.config
  packages/create-plugin/templates/datasource/provisioning/datasources/datasources.yml
  packages/create-plugin/templates/datasource/src/datasource.ts
  packages/create-plugin/templates/datasource/src/types.ts
  packages/create-plugin/templates/datasource/tests/configEditor.spec.ts
  packages/create-plugin/templates/datasource/tests/queryEditor.spec.ts
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
  packages/create-plugin/templates/panel/provisioning/dashboards/dashboard.json
  packages/create-plugin/templates/panel/provisioning/datasources/datasources.yml
  packages/create-plugin/templates/panel/src/components/SimplePanel.tsx
  packages/create-plugin/templates/panel/tests/panel.spec.ts
Labels: create-plugin, minor, release

#858 Docs: Plugin E2E - Update docs
  docusaurus/docs/e2e-test-a-plugin/ci.md
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/introduction.md
  docusaurus/docs/e2e-test-a-plugin/migrate-from-grafana-e2e.md
  docusaurus/docs/get-started/folder-structure.md
  docusaurus/docs/migration-guides/angular-react/angular-react-convert-from-time_series2.md
  docusaurus/docs/snippets/plugin-e2e-create-ds-plugin.npm.md
  docusaurus/docs/snippets/plugin-e2e-create-ds-plugin.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-create-ds-plugin.yarn.md
Labels: no-changelog

#862 Create Plugin: set plugin-e2e to ^1.0.1
  packages/create-plugin/templates/common/_package.json
Labels: patch, release

#826 Docs: Add a router or multiplexer
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-router.md
Labels: type/docs, no-changelog

#803 Docs: Clarify exception for signing plugin
  docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
  docusaurus/docs/publish-a-plugin/sign-a-plugin.md
Labels: type/docs, no-changelog

#864 Revert "Docs: Add a router or multiplexer"
  docusaurus/docs/create-a-plugin/extend-a-plugin/add-router.md
Labels: no-changelog

#852 Docs: Plugin E2E - Panel plugin docs
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/migrate-from-grafana-e2e.md
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/annotation-queries.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/custom-variable-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-panel-plugin.md
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
Labels: no-changelog

#865 Plugin E2E: Click on panel menu items
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/models/components/Panel.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelMenu.spec.ts
Labels: minor, release

#866 Docs: Add plugin-e2e to NPM packages table
  README.md
Labels: type/docs, no-changelog

#868 Build: Introduce stricter typechecking
  packages/create-plugin/src/utils/utils.packageManager.ts
  packages/create-plugin/src/utils/utils.templates.ts
  packages/plugin-e2e/src/fixtures/isFeatureToggleEnabled.ts
  packages/plugin-e2e/src/models/pages/ExplorePage.ts
  packages/plugin-e2e/src/models/pages/PluginConfigPage.ts
  tsconfig.base.json
Labels: patch, release

#884 Docs: Update backend introduction
  docusaurus/docs/introduction/backend.md
Labels: type/docs, no-changelog

#882 Create plugin: Replace all mentions of plop in contributing / comments
  packages/create-plugin/CONTRIBUTING.md
  packages/create-plugin/src/constants.ts
Labels: type/docs, no-changelog

#885 Docs: Plugin E2E - Using the api article
  docusaurus/docs/e2e-test-a-plugin/authentication.md
  docusaurus/docs/e2e-test-a-plugin/feature-toggles.md
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/use-the-api.md
  packages/plugin-e2e/src/types.ts
Labels: no-changelog

#881 Docs: Update the docs for UI-Extensions
  docusaurus/docs/ui-extensions/create-an-extension-point.md
Labels: type/docs, no-changelog

#883 Create Plugins: Use non dev docker image on e2e
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/common/docker-compose.yaml
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
Labels: create-plugin, minor, release

#892 Create plugin: update scaffolded tests when creating an app plugin
  packages/create-plugin/templates/app/tests/appConfig.spec.ts
  packages/create-plugin/templates/app/tests/appNavigation.spec.ts
  packages/create-plugin/templates/app/tests/fixtures.ts
Labels: minor, release

#893 Docs: Update the `plugin.json` reference
  docusaurus/docs/metadata.md
Labels: type/docs, no-changelog

#683 Docs: Add doc for event bus of PanelProps
  docusaurus/docs/create-a-plugin/develop-a-plugin/panel-properties.md
Labels: type/docs, no-changelog
