Repository grafana/plugin-tools, pull requests merged in 2024-09, with the labels that each got.

#996 Docs: Profiling a backend plugin
  docusaurus/docs/how-to-guides/data-source-plugins/profile-backend-plugin.md
Labels: type/docs, no-changelog

#1072 Create Plugin: Code split scaffolded apps
  docusaurus/docs/get-started/best-practices.md
  docusaurus/docs/reference/metadata.md
  packages/create-plugin/templates/app/src/components/App/App.test.tsx
  packages/create-plugin/templates/app/src/components/App/App.tsx
  packages/create-plugin/templates/app/src/components/App/index.tsx
  packages/create-plugin/templates/app/src/components/AppConfig/AppConfig.test.tsx
  packages/create-plugin/templates/app/src/components/AppConfig/AppConfig.tsx
  packages/create-plugin/templates/app/src/components/AppConfig/index.tsx
  packages/create-plugin/templates/app/src/module.ts
  packages/create-plugin/templates/app/src/module.tsx
  packages/create-plugin/templates/app/src/pages/PageFour.tsx
  packages/create-plugin/templates/app/src/pages/PageOne.tsx
  packages/create-plugin/templates/app/src/pages/PageThree.tsx
  packages/create-plugin/templates/app/src/pages/PageTwo.tsx
  packages/create-plugin/templates/app/src/pages/index.tsx
  packages/create-plugin/templates/common/.config/jest-setup.js
  packages/create-plugin/templates/scenes-app/src/components/App/App.tsx
  packages/create-plugin/templates/scenes-app/src/components/App/index.tsx
  packages/create-plugin/templates/scenes-app/src/components/AppConfig/AppConfig.tsx
  packages/create-plugin/templates/scenes-app/src/components/AppConfig/index.tsx
  packages/create-plugin/templates/scenes-app/src/components/Routes/Routes.tsx
  packages/create-plugin/templates/scenes-app/src/components/Routes/index.tsx
  packages/create-plugin/templates/scenes-app/src/module.ts
  packages/create-plugin/templates/scenes-app/src/module.tsx
  packages/create-plugin/templates/scenes-app/src/pages/HelloWorld/HelloWorld.tsx
  packages/create-plugin/templates/scenes-app/src/pages/HelloWorld/index.tsx
  packages/create-plugin/templates/scenes-app/src/pages/Home/Home.tsx
  packages/create-plugin/templates/scenes-app/src/pages/Home/index.tsx
  packages/create-plugin/templates/scenes-app/src/pages/WithDrilldown/WithDrilldown.tsx
  packages/create-plugin/templates/scenes-app/src/pages/WithDrilldown/index.tsx
  packages/create-plugin/templates/scenes-app/src/pages/WithTabs/WithTabs.tsx
  packages/create-plugin/templates/scenes-app/src/pages/WithTabs/index.tsx
Labels: create-plugin, patch, release

#1093 Chore: Remove unused grafana/ts-config package
  package-lock.json
  package.json
Labels: chore, no-changelog

#1019 Docs: Add RBAC guide for app plugins
  docusaurus/docs/how-to-guides/app-plugins/implement-rbac-in-app-plugins.md
Labels: type/docs, no-changelog

#1098 Chore: Bump uuid
  package-lock.json
  packages/plugin-e2e/package.json
Labels: patch, release

#1095 Website: Bump webpack to 5.94.x
  package-lock.json
Labels: dependencies, chore, no-changelog

#1096 Docs: Add content for template variables
  docusaurus/docs/how-to-guides/data-source-plugins/add-support-for-variables.md
Labels: type/docs, no-changelog

#1099 Chore: Automerge Grafana dependency updates in create-plugin templates
  .github/renovate.json
Labels: no-changelog

#1090 Documentation: Add info for `multiValueFilterOperators`
  docusaurus/docs/reference/metadata.md
Labels: type/docs, no-changelog, documentation

#1101 Chore: Let depedabot handle plugin-e2e dep updates
  .github/dependabot.yml
Labels: no-changelog

#1100 Docs: Auto instrumentation update
  docusaurus/docs/how-to-guides/data-source-plugins/add-logs-metrics-traces-for-backend-plugins.md
Labels: type/docs, no-changelog

#1081 Docs: Add/update resource handler topics for datasource and app plugins
  docusaurus/docs/how-to-guides/app-plugins/add-resource-handler.md
  docusaurus/docs/how-to-guides/data-source-plugins/add-resource-handler.md
  docusaurus/docs/shared/implement-resource-handler.md
Labels: type/docs, no-changelog

#1109 Docs: Minor fix for resource handler topics
  docusaurus/docs/shared/implement-resource-handler.md
Labels: type/docs, no-changelog

#1111 Plugin E2E: Allow overriding `waitUntil` in goto page fixtures
  packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts
  packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/pages/AnnotationPage.ts
  packages/plugin-e2e/src/models/pages/AppPage.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/src/models/pages/ExplorePage.ts
  packages/plugin-e2e/src/models/pages/GrafanaPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/src/models/pages/PluginConfigPage.ts
  packages/plugin-e2e/src/models/pages/VariableEditPage.ts
  packages/plugin-e2e/src/models/pages/VariablePage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/page-loading/goto.spec.ts
Labels: minor, release

#1097 Plugin E2E: Describe how to start e2e test server in contributing docs
  package-lock.json
  packages/plugin-e2e/.env.example
  packages/plugin-e2e/CONTRIBUTING.md
  packages/plugin-e2e/docker-compose.yaml
  packages/plugin-e2e/package.json
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
Labels: no-changelog

#1033 Docs: Improve documentation for plugins ReqAction
  docusaurus/docs/reference/metadata.md
Labels: type/docs, no-changelog

#1125 Adds announcement bar to promote the use of the grafana community forum for plugin developers
  docusaurus/website/docusaurus.config.js
Labels: type/docs, no-changelog, skip-release

#1122 Use centralized 'Add to docs project' workflow with GitHub App auth
  .github/issue_commands.json
  .github/workflows/add-to-docs-project.yml
  .github/workflows/typedocs.yml
Labels: no-changelog

#1127 Feat: Adding provenance publish config
  .github/workflows/ci.yml
  packages/create-plugin/package.json
  packages/plugin-e2e/package.json
  packages/plugin-meta-extractor/package.json
  packages/sign-plugin/package.json
Labels: enhancement, patch

#1092 Types Bundler: Add package
  docusaurus/docs/how-to-guides/data-source-plugins/add-support-for-variables.md
  docusaurus/docs/reference/metadata.md
  package-lock.json
  package.json
  packages/plugin-types-bundler/LICENSE
  packages/plugin-types-bundler/README.md
  packages/plugin-types-bundler/package.json
  packages/plugin-types-bundler/src/bin/run.ts
  packages/plugin-types-bundler/src/bundleTypes.ts
  packages/plugin-types-bundler/src/utils.ts
  packages/plugin-types-bundler/tsconfig.json
Labels: enhancement, patch, release

#1132 Chore: Clean up husky
  .husky/pre-commit
  package.json
Labels: chore, no-changelog

#1136 docs: update min grafana version
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/tutorials/build-a-data-source-backend-plugin.md
  docusaurus/docs/tutorials/build-a-data-source-plugin.md
  docusaurus/docs/tutorials/build-a-panel-plugin-with-d3.md
  docusaurus/docs/tutorials/build-a-panel-plugin.md
  docusaurus/docs/tutorials/build-an-app-plugin.md
Labels: no-changelog, documentation

#1137 Chore: Fixing path-to-regexp
  package-lock.json
  package.json
Labels: dependencies, chore

#1138 Chore: bumping dompurify package
  package-lock.json
Labels: no-changelog

#1117 Docs: Fix 2 anchors on profile backend plugin topic
  docusaurus/docs/how-to-guides/data-source-plugins/profile-backend-plugin.md
Labels: type/docs, no-changelog

#1133 Switch to createDataFrame
  docusaurus/docs/how-to-guides/data-source-plugins/add-features-for-explore-queries.md
  docusaurus/docs/tutorials/build-a-data-source-plugin.md
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/datasource/src/datasource.ts
Labels: patch, documentation

#1144 Update dashboard variables settings URL
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
Labels: patch, release

#1149 Website: bump webpack to latest
  package-lock.json
Labels: chore, no-changelog

#1143 Create Plugin: Update go sdk when running update cmd
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/utils/utils.goSdk.ts
Labels: create-plugin, minor, release

#1120 Adds Anatomy of a Plugin documentation which supercedes the Folder structure page
  docusaurus/docs/get-started/best-practices.md
  docusaurus/docs/get-started/folder-structure.md
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/key-concepts/anatomy-of-a-plugin.md
  docusaurus/docs/key-concepts/images/app-configuration.png
  docusaurus/docs/key-concepts/images/app-pages.png
  docusaurus/docs/key-concepts/images/app-plugin.png
  docusaurus/docs/key-concepts/images/data-source-plugin.png
  docusaurus/docs/key-concepts/images/datasource-configeditor.png
  docusaurus/docs/key-concepts/images/datasource-healthcheck.png
  docusaurus/docs/key-concepts/images/datasource-queryeditor.png
  docusaurus/docs/key-concepts/images/panel-options.png
  docusaurus/docs/key-concepts/images/panel-plugin.png
  docusaurus/docs/key-concepts/images/panel-visualization.png
  docusaurus/docs/key-concepts/images/plugin-types.png
  docusaurus/docs/key-concepts/images/ui-extension.png
  docusaurus/website/README.md
Labels: type/docs, no-changelog

#1151 Adds redirect from old folder structure page to anatomy page
  docusaurus/website/docusaurus.config.base.js
Labels: type/docs, no-changelog
