Repository grafana/plugin-tools, pull requests merged in 2024-10, with the labels that each got.

#1155 Plugin E2e: Support scenes powered dashboard UI
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/pages.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/dashboards/dashboard.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.spec.ts
Labels: patch, release

#1159 Chore: bump uplot to 1.6.31
  package-lock.json
  packages/plugin-meta-extractor/package.json
Labels: no-changelog, skip-release

#1139 Create Plugin: Remove topnav feature flag from Scenes templates
  packages/create-plugin/templates/scenes-app/src/pages/Home/Home.tsx
Labels: create-plugin, patch, release

#999 Create Plugin: Support SRI in dynamic imported chunks
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
  packages/create-plugin/templates/common/_package.json
Labels: create-plugin, minor, release

#1163 Docs: Update the meta-data reference for extensions
  docusaurus/docs/reference/metadata.md
Labels: no-changelog, documentation

#1160 chore: update shields.io template
  packages/create-plugin/templates/common/src/README.md
Labels: create-plugin, patch, release

#1168 Remove "Add to docs project" workflow
  .github/workflows/add-to-docs-project.yml
Labels: no-changelog

#1166 Create Plugin: Stop prettier from writing files outside the target path
  packages/create-plugin/src/utils/utils.prettifyFiles.ts
Labels: create-plugin, patch, release

#1173 Renovate: Fix update config
  .github/renovate.json5
Labels: chore, no-changelog

#1178 CI: Fix renovate auto and docusaurus grouping
  .github/renovate.json5
Labels: no-changelog, ci

#1181 Renovate: Add packageRule for minor and major dep bumps
  .github/renovate.json5
Labels: no-changelog, ci

#1197 CI: Use check-labels to label renovate PRs
  .github/actions/check-labels/index.js
  .github/renovate.json5
  .github/workflows/check-labels.yml
Labels: no-changelog, ci

#1200 CI: Fix check-labels action removing labels
  .github/actions/check-labels/index.js
Labels: no-changelog, ci

#1204 CI: Fix request error when setting labels
  .github/actions/check-labels/index.js
Labels: chore, no-changelog

#1208 Update get-started.mdx
  docusaurus/docs/get-started/get-started.mdx
Labels: type/docs, no-changelog

#1210 Create Plugin: Remove mkdirp package
  package-lock.json
  packages/create-plugin/package.json
  packages/create-plugin/src/utils/utils.templates.ts
Labels: create-plugin, patch, chore

#1158 Adds a plugin publishing best practices guide.
  docusaurus/docs/publish-a-plugin/publish-or-update-a-plugin.md
  docusaurus/docs/publish-a-plugin/publishing-best-practices.md
Labels: type/docs, no-changelog

#1214 Docs: Ensure that destination equals source by using rsync
  .github/workflows/deploy-to-developer-portal-dev.yml
  .github/workflows/deploy-to-developer-portal-prod.yml
Labels: chore, no-changelog, documentation

#1223 Plugin E2E: Fix broken tests
  packages/plugin-e2e/tests/as-viewer-user/permissions.spec.ts
  packages/plugin-e2e/tests/as-viewer-user/permissions/createUserUsingValidCredentials.spec.ts
Labels: no-changelog

#1219 Replace `wait for` docker call with our custom github action
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.yarn.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.yarn.md
  packages/create-plugin/templates/github/workflows/ci.yml
Labels: no-changelog

#1211 Create Plugin: Introduce create plugin update workflow
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/github/workflows/cp-update.yml
Labels: create-plugin, minor, release

#1244 Config: check environment for Grafana admin URL, username, and password
  docusaurus/docs/e2e-test-a-plugin/authentication.md
  packages/create-plugin/templates/common/playwright.config
  packages/plugin-e2e/README.md
  packages/plugin-e2e/src/options.ts
Labels: minor, release

#1246 Update anatomy doc with higher resolution images
  docusaurus/docs/key-concepts/images/app-configuration.png
  docusaurus/docs/key-concepts/images/app-pages.png
  docusaurus/docs/key-concepts/images/datasource-configeditor.png
  docusaurus/docs/key-concepts/images/datasource-healthcheck.png
  docusaurus/docs/key-concepts/images/datasource-queryeditor.png
  docusaurus/docs/key-concepts/images/panel-options.png
  docusaurus/docs/key-concepts/images/panel-visualization.png
Labels: type/docs, no-changelog

#1253 Create Plugin: Fix broken panel test
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/panel/tests/panel.spec.ts
Labels: patch, release

#1250 Dependencies: Follow e2e-selectors modified tag
  .github/renovate.json5
  packages/create-plugin/templates/common/_package.json
Labels: no-changelog

#1243 Fix: Dont default navigation page permissions to admin
  docusaurus/docs/tutorials/build-an-app-plugin.md
  packages/create-plugin/templates/app/src/plugin.json
  packages/create-plugin/templates/scenes-app/src/plugin.json
Labels: create-plugin, patch, release

#1256 Renovate: Merge e2e-selector package rules
  .github/renovate.json5
Labels: no-changelog

#1268 Renovate: Adjust e2e-selectors dependency management
  .github/renovate.json5
  packages/create-plugin/templates/common/_package.json
Labels: no-changelog

#1261 docs: decryptedSecureJsonData from instance settings
  docusaurus/docs/how-to-guides/data-source-plugins/add-authentication-for-data-source-plugins.md
Labels: no-changelog, documentation

#1240 Docs: Add required/optional info to folder structure
  docusaurus/docs/key-concepts/anatomy-of-a-plugin.md
Labels: type/docs, no-changelog

#1271 Renovate: Update rules for es-lint config and selectors
  .github/renovate.json5
Labels: no-changelog

#1269 Types Bundler: Add debugger and process args
  package-lock.json
  packages/plugin-types-bundler/package.json
  packages/plugin-types-bundler/src/args.ts
  packages/plugin-types-bundler/src/bin/run.ts
  packages/plugin-types-bundler/src/bundleTypes.ts
  packages/plugin-types-bundler/src/debug.ts
Labels: patch, release

#1249 Add guide for migrating queries for backend datasources
  docusaurus/docs/how-to-guides/data-source-plugins/add-migration-handler-for-backend.md
Labels: no-changelog
