Repository grafana/plugin-tools, pull requests merged in 2024-02, with the labels that each got.

#705 Create-plugin: Check for a clean working tree
  package-lock.json
  packages/create-plugin/package.json
  packages/create-plugin/src/bin/run.ts
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/utils/utils.console.ts
  packages/create-plugin/src/utils/utils.git.ts
Labels: minor, release

#706 Create-plugin: Check if inside a plugin directory
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/utils/utils.plugin.ts
Labels: minor, release

#708 Docs: Remove zip download link
  docusaurus/docs/publish-a-plugin/build-automation.md
Labels: type/docs, no-changelog

#709 Docs: Add RBAC role definition, include and route action protection
  docusaurus/docs/metadata.md
Labels: type/docs, no-changelog

#696 Fix broken livereload injection when using Grafana 10.2.3
  packages/create-plugin/templates/common/.config/Dockerfile
Labels: patch, release

#711 Update create-plugin workflow action versions
  packages/create-plugin/templates/github/ci/.github/workflows/ci.yml
  packages/create-plugin/templates/github/ci/.github/workflows/release.yml
  packages/create-plugin/templates/github/is-compatible/.github/workflows/is-compatible.yml
Labels: minor, release

#710 Create-plugin: Use react-router v6 by default
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/types.ts
  packages/create-plugin/src/utils/utils.config.ts
  packages/create-plugin/src/utils/utils.templates.ts
  packages/create-plugin/templates/app/src/components/App/App.tsx
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
  packages/create-plugin/templates/common/.cprc.json
  packages/create-plugin/templates/common/_package.json
Labels: minor, release

#626 Docs: Add reference to Cloud token on GitHub workflows topic
  docusaurus/docs/create-a-plugin/develop-a-plugin/set-up-github-workflows.md
Labels: type/docs, no-changelog

#664 angular to react configuration migration guide
  docusaurus/docs/migration-guides/angular-react/configuration-migration.md
Labels: type/docs, no-changelog

#725 Plugin E2E: Add root folder to all tests
  packages/plugin-e2e/playwright.config.ts
  packages/plugin-e2e/tests/admin/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/explore/queryEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/admin/datasource/feature-toggles/queryEditor.sync.spec.ts
  packages/plugin-e2e/tests/admin/datasource/mocks/resource.ts
  packages/plugin-e2e/tests/admin/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/query-editor/queryEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/variables/customVariableEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/variables/variableInterpolation.spec.ts
  packages/plugin-e2e/tests/admin/panel/panel.spec.ts
  packages/plugin-e2e/tests/auth.setup.ts
Labels: no-changelog

#722 Create Plugin: Run prettier on .config after update
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/generate/prettify-files.ts
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/utils/utils.packagejson.ts
  packages/create-plugin/src/utils/utils.prettifyFiles.ts
Labels: minor, release

#727 Plugin E2E: Update workflow
  .github/workflows/playwright.yml
  packages/plugin-e2e/tests/admin/datasource/explore/queryEditor.integration.spec.ts
Labels: no-changelog

#730 Plugin E2E: Fix feature toggles race condition
  packages/plugin-e2e/src/fixtures/scripts/overrideFeatureToggles.js
Labels: patch, release, type/bug

#733 Plugin E2E: Generate dts files
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/tsconfig.json
Labels: patch, release

#688 Plugin E2E: Enable assertion on panel data
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/components.ts
  packages/plugin-e2e/src/models/DashboardPage.ts
  packages/plugin-e2e/src/models/ExplorePage.ts
  packages/plugin-e2e/src/models/Panel.ts
  packages/plugin-e2e/src/models/PanelEditPage.ts
  packages/plugin-e2e/src/models/utils.ts
  packages/plugin-e2e/tests/admin/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/admin/datasource/explore/queryEditor.integration.spec.ts
Labels: minor, release

#732 Plugin E2E:: Add back health check mock
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
Labels: patch, release

#741 Plugin E2E: Fix typing in config page
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
Labels: patch, release

#704 Plugin E2E: Refactor workflow file
  .github/workflows/playwright.yml
Labels: no-changelog

#707 Create-plugin: Change how the `update` command works
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/utils/utils.plugin.ts
Labels: major, release

#746 Create plugin: Fix update command
  package-lock.json
  packages/create-plugin/package.json
  packages/create-plugin/src/bin/run.ts
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/types.ts
  packages/create-plugin/src/utils/utils.cli.ts
  packages/create-plugin/src/utils/utils.config.ts
  packages/create-plugin/src/utils/utils.templates.ts
Labels: patch, release, type/bug

#740 Plugin E2E: Add fixture that reads provisioned data source files
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/commands/createDataSource.ts
  packages/plugin-e2e/src/fixtures/commands/readProvisionedDataSource.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/models/DataSourceConfigPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/admin/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/admin/datasource/feature-toggles/queryEditor.sync.spec.ts
  packages/plugin-e2e/tests/admin/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/admin/datasource/query-editor/queryEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/variables/customVariableEditor.spec.ts
  packages/plugin-e2e/tests/admin/datasource/variables/customVariableQueryRunner.integration.spec.ts
Labels: minor, release

#726 Plugin E2E: Improved support for multiple users and roles
  packages/plugin-e2e/playwright.config.ts
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/auth/auth.setup.ts
  packages/plugin-e2e/src/fixtures/commands/createUser.ts
  packages/plugin-e2e/src/fixtures/commands/login.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/options/index.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.sync.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/mocks/resource.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/variableInterpolation.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panel.spec.ts
  packages/plugin-e2e/tests/as-viewer-user/overridePermissions.spec.ts
  packages/plugin-e2e/tests/as-viewer-user/permissions.spec.ts
Labels: minor, release

#701 Docs: Plugin E2E: Getting started docs
  docusaurus/docs/create-a-plugin/develop-a-plugin/set-up-github-workflows.md
  docusaurus/docs/e2e-test-a-plugin/_category_.json
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/introduction.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-ds-workflow.yarn.md
  docusaurus/docs/snippets/plugin-e2e-install.npm.md
  docusaurus/docs/snippets/plugin-e2e-install.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-install.yarn.md
  docusaurus/docs/snippets/plugin-e2e-run-tests.npm.md
  docusaurus/docs/snippets/plugin-e2e-run-tests.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-run-tests.yarn.md
  docusaurus/docs/snippets/plugin-e2e-start-grafana.npm.md
  docusaurus/docs/snippets/plugin-e2e-start-grafana.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-start-grafana.yarn.md
  packages/plugin-e2e/README.md
Labels: type/docs, no-changelog

#752 Plugin-E2E: Split models into pages and components
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/explorePage.ts
  packages/plugin-e2e/src/models/components/DataSourcePicker.ts
  packages/plugin-e2e/src/models/components/Panel.ts
  packages/plugin-e2e/src/models/components/TimeRange.ts
  packages/plugin-e2e/src/models/index.ts
  packages/plugin-e2e/src/models/pages/AnnotationEditPage.ts
  packages/plugin-e2e/src/models/pages/AnnotationPage.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/src/models/pages/DataSourceConfigPage.ts
  packages/plugin-e2e/src/models/pages/ExplorePage.ts
  packages/plugin-e2e/src/models/pages/GrafanaPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/src/models/pages/VariableEditPage.ts
  packages/plugin-e2e/src/models/pages/VariablePage.ts
Labels: minor, release

#745 Docs: Plugin E2E - Add locating elements article
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
Labels: no-changelog

#749 Plugin E2E: Add fixture that reads provisioned dashboard files
  packages/plugin-e2e/src/api.ts
  packages/plugin-e2e/src/fixtures/commands/readProvision.ts
  packages/plugin-e2e/src/fixtures/commands/readProvisionedDashboard.ts
  packages/plugin-e2e/src/fixtures/commands/readProvisionedDataSource.ts
  packages/plugin-e2e/src/fixtures/index.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/variableInterpolation.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panel.spec.ts
Labels: minor, release

#744 Docs: Plugin E2E - Add authentication article
  docusaurus/docs/e2e-test-a-plugin/authentication.md
Labels: no-changelog

#755 Plugin-e2e: Add yaml as a dependency
  package-lock.json
  packages/plugin-e2e/package.json
Labels: patch, release, plugin-e2e

#754 Create Plugin: Add tests for config
  package-lock.json
  package.json
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/constants.ts
  packages/create-plugin/src/utils/tests/utils.config.test.ts
  packages/create-plugin/src/utils/utils.config.ts
  packages/create-plugin/src/utils/utils.templates.ts
  tsconfig.base.json
Labels: patch, release

#674 create-plugin: update grafana version to `v10.3.3`
  packages/create-plugin/src/constants.ts
  packages/create-plugin/templates/common/_package.json
Labels: create-plugin, minor, release, chore

#718 Docs: Migrate to react-router v6
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md
Labels: type/docs, no-changelog

#738 Website: Include dashboards doc
  docusaurus/docs/create-a-plugin/extend-a-plugin/include-dashboards.md
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/src/css/custom.css
  docusaurus/website/static/img/app-dashboard-ds-select.png
  docusaurus/website/static/img/app-dashboard-ds-variable.png
  docusaurus/website/static/img/create-access-policy-token.png
  docusaurus/website/static/img/create-access-policy-v2.png
  docusaurus/website/static/img/create-alert.png
  docusaurus/website/static/img/hero_banner.png
  docusaurus/website/static/img/panel_error.png
  docusaurus/website/static/img/plugins-submission-create.png
  docusaurus/website/static/img/ui-extensions-menu.png
Labels: type/docs, no-changelog

#748 Docs: Plugin E2E - Add Setup Resources article
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
Labels: no-changelog

#753 Docs: Plugin E2E - Get started follow up
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
  docusaurus/docs/snippets/plugin-e2e-create-ds-plugin.npm.md
  docusaurus/docs/snippets/plugin-e2e-create-ds-plugin.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-create-ds-plugin.yarn.md
  packages/plugin-e2e/README.md
Labels: no-changelog

#723 Docs: Plugin E2E - Add feature toggles article
  docusaurus/docs/e2e-test-a-plugin/feature-toggles.md
Labels: no-changelog

#757 Plugin E2E: Bump Playwright version
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  package-lock.json
  packages/plugin-e2e/README.md
  packages/plugin-e2e/package.json
Labels: minor, release

#734 docs: Update set-up-github-workflows.md
  docusaurus/docs/create-a-plugin/develop-a-plugin/set-up-github-workflows.md
Labels: type/docs, no-changelog

#770 Chore: Bump to latest version of auto
  package-lock.json
  package.json
Labels: no-changelog

#776 Docs: Use correct panel context type in extension example
  docusaurus/docs/ui-extensions/register-an-extension.md
Labels: no-changelog

#775 Chore: avoid race conditions in label checks
  .github/workflows/check-labels.yml
Labels: chore, no-changelog, github_actions

#774 Docs: Adding docusaurus redirects plugin
  CONTRIBUTING.md
  docusaurus/website/docusaurus.config.base.js
  docusaurus/website/package.json
  package-lock.json
Labels: chore, no-changelog, skip-release

#764 Create Plugin: Bump Glob to 10.x.x
  package-lock.json
  packages/create-plugin/package.json
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/provisioning.command.ts
  packages/create-plugin/src/utils/utils.templates.ts
Labels: dependencies, create-plugin, patch

#781 Docs: Add 11.x migration guide
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.x-v11.x.md
Labels: type/docs, no-changelog

#786 Create Plugin: Bump go version in backend plugin scaffolding
  .github/workflows/ci.yml
  packages/create-plugin/templates/backend-app/go.mod
  packages/create-plugin/templates/backend/go.mod
Labels: patch, release

#778 Docs: Plugin-E2E: Docs improvements
  docusaurus/docs/e2e-test-a-plugin/_category_.json
  docusaurus/docs/e2e-test-a-plugin/authentication.md
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
  docusaurus/docs/e2e-test-a-plugin/setup-resources.md
Labels: no-changelog

#785 Plugin E2E: Improve ds config Save & test for FE plugins
  packages/plugin-e2e/docker-compose.yaml
  packages/plugin-e2e/src/e2e-selectors/types.ts
  packages/plugin-e2e/src/e2e-selectors/versioned/apis.ts
  packages/plugin-e2e/src/models/pages/DataSourceConfigPage.ts
  packages/plugin-e2e/src/types.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
Labels: minor, release

#784 docs: specify frontend and backend can be included
  docusaurus/docs/create-a-plugin/extend-a-plugin/nested-plugins.mdx
Labels: type/docs, no-changelog

#777 Docs: Plugin E2E - CI article
  docusaurus/docs/e2e-test-a-plugin/ci.md
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/selecting-ui-elements.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.npm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-fe-plugin-workflow.yarn.md
  docusaurus/website/static/img/e2e-version-plugin-dependency.png
  docusaurus/website/static/img/e2e-version-version-support-policy.png
Labels: no-changelog

#760 Docs: Plugin E2E - Config page article
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/_category_.json
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/configuration-editor.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/index.md
Labels: no-changelog

#761 Docs: Plugin E2E - Query editor article
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/query-editor.md
  packages/plugin-e2e/src/models/pages/GrafanaPage.ts
Labels: no-changelog
