Repository grafana/plugin-tools, pull requests merged in 2025-08, with the labels that each got.

#2005 Chore: fix formatting in cursor/mcp.json
  .cursor/mcp.json
Labels: chore, no-changelog

#2000 CI: reconfigure renovate
  .github/renovate.json5
Labels: no-changelog

#2011 Moving minimumReleaseAge to the root level
  .github/renovate.json5
Labels: no-changelog

#2012 Chore: Put back optionalDependencies for local dev
  package-lock.json
  package.json
Labels: chore, no-changelog

#1942 Create Plugin: Add package.json utils for migrations
  packages/create-plugin/src/migrations/scripts/003-update-eslint-deprecation-rule.test.ts
  packages/create-plugin/src/migrations/scripts/003-update-eslint-deprecation-rule.ts
  packages/create-plugin/src/migrations/utils.test.ts
  packages/create-plugin/src/migrations/utils.ts
Labels: patch, release

#2017 Plugin e2e: fix color picker selector
  packages/plugin-e2e/src/models/components/ColorPicker.ts
  packages/plugin-e2e/tests/as-admin-user/page-loading/goto.spec.ts
Labels: patch, release

#2015 CI: Use self hosted runners
  .github/workflows/check-labels.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-to-developer-portal-dev.yml
  .github/workflows/deploy-to-developer-portal-prod.yml
  .github/workflows/lapo-create-pr.yml
  .github/workflows/lapo-generate-embeddings.yml
  .github/workflows/playwright.yml
  .github/workflows/stale-branches.yml
  .github/workflows/stale.yml
  .github/workflows/test-build.yml
Labels: no-changelog, ci

#2018 Docs: Extensions API style edits
  docusaurus/docs/reference/ui-extensions.md
Labels: type/docs, no-changelog

#2025 Docs: Missing Landings - e2e tests
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/index.md
  docusaurus/docs/e2e-test-a-plugin/introduction.md
  docusaurus/docs/e2e-test-a-plugin/migrate-from-grafana-e2e.md
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/index.md
  docusaurus/docs/e2e-test-a-plugin/test-a-panel-plugin.md
  docusaurus/docs/e2e-test-a-plugin/test-an-app-plugin/index.md
  docusaurus/docs/e2e-test-a-plugin/use-the-api.md
  docusaurus/docs/how-to-guides/runtime-checks.md
  docusaurus/docs/key-concepts/anatomy-of-a-plugin.md
  docusaurus/docs/publish-a-plugin/publishing-best-practices.md
  docusaurus/website/sidebars.ts
  packages/plugin-e2e/README.md
Labels: type/docs, no-changelog

#2042 Docs: Improvements to log debugging
  docusaurus/docs/how-to-guides/ui-extensions/debug-logs.md
Labels: type/docs, no-changelog

#2045 CI: use gh hosted runner for npm provenance
  .github/workflows/ci.yml
Labels: no-changelog, ci

#2046 docs: updates meta data for plugin json
  docusaurus/docs/reference/metadata.md
Labels: type/docs, no-changelog

#2053 Plugin e2e: Fix AlertRuleEditPage evaluate flakiness
  packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts
Labels: patch, release, plugin-e2e

#2065 Revert "CI: use OIDC for publishing NPM packages"
  .github/workflows/ci.yml
Labels: no-changelog

#2059 Docs: Backend edits
  docusaurus/docs/e2e-test-a-plugin/ci.md
  docusaurus/docs/get-started/best-practices.md
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/get-started/set-up-development-environment.mdx
  docusaurus/docs/how-to-guides/app-plugins/add-authentication-for-app-plugins.md
  docusaurus/docs/how-to-guides/app-plugins/add-backend-component.md
  docusaurus/docs/how-to-guides/data-source-plugins/add-authentication-for-data-source-plugins.md
  docusaurus/docs/how-to-guides/data-source-plugins/add-router.md
  docusaurus/docs/how-to-guides/data-source-plugins/convert-a-frontend-datasource-to-backend.md
  docusaurus/docs/how-to-guides/data-source-plugins/profile-backend-plugin.md
  docusaurus/docs/key-concepts/backend-plugins/grafana-plugin-sdk-for-go.md
  docusaurus/docs/key-concepts/backend-plugins/index.md
  docusaurus/docs/key-concepts/backend-plugins/plugin-protocol.md
  docusaurus/docs/key-concepts/plugin-lifecycle.md
  docusaurus/docs/publish-a-plugin/sign-a-plugin.md
  docusaurus/docs/tutorials/build-an-app-plugin.md
  docusaurus/website/sidebars.ts
  packages/create-plugin/templates/_partials/backend-getting-started.md
  packages/create-plugin/templates/backend-app/pkg/plugin/app.go
Labels: type/docs, no-changelog

#2066 Docs: Extensions new IA, functions
  docusaurus/docs/how-to-guides/ui-extensions/create-an-extension-point.md
  docusaurus/docs/how-to-guides/ui-extensions/debug-logs.md
  docusaurus/docs/how-to-guides/ui-extensions/degregate-ui.md
  docusaurus/docs/how-to-guides/ui-extensions/expose-a-component.md
  docusaurus/docs/how-to-guides/ui-extensions/extension-user-render-component.md
  docusaurus/docs/how-to-guides/ui-extensions/index.md
  docusaurus/docs/how-to-guides/ui-extensions/register-an-extension.md
  docusaurus/docs/how-to-guides/ui-extensions/use-an-exposed-component.md
  docusaurus/docs/how-to-guides/ui-extensions/versioning-extensions.md
  docusaurus/docs/key-concepts/ui-extensions.md
  docusaurus/docs/reference/metadata.md
  docusaurus/docs/reference/ui-extensions-reference/extension-points.md
  docusaurus/docs/reference/ui-extensions-reference/extensions-api-deprecated.md
  docusaurus/docs/reference/ui-extensions-reference/index.md
  docusaurus/docs/reference/ui-extensions-reference/ui-extensions.md
  docusaurus/docs/shared/extension-points.md
  docusaurus/website/sidebars.ts
Labels: type/docs, no-changelog
