Repository grafana/plugin-tools, pull requests merged in 2025-04, with the labels that each got.

#1676 Change github-app-fixed-hash
  .github/workflows/lapo-create-pr.yml
Labels: no-changelog

#1678 CI: Fix github app token parameter names
  .github/workflows/lapo-create-pr.yml
Labels: no-changelog

#1639 Docs: Add migration guide for UI extensions in Grafana 12
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.0.x-v10.1.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v10.x-v11.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v11.6.x-v12.0.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v6.x-v7.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v7.x-v8.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.3.x-8.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v8.x-v9.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.1.x-v9.2.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.3.x-9.4.x.md
  docusaurus/docs/migration-guides/update-from-grafana-versions/v9.x-v10.x.md
  docusaurus/website/babel.config.js
Labels: type/docs, no-changelog

#1685 CODEOWNERS: update to @grafana/plugins-platform
  .github/CODEOWNERS
Labels: chore, no-changelog

#1656 Chore: Pin all github external actions versions
  .github/workflows/check-labels.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-to-developer-portal-dev.yml
  .github/workflows/deploy-to-developer-portal-prod.yml
  .github/workflows/playwright.yml
  .github/workflows/stale-branches.yml
  .github/workflows/stale.yml
  .github/workflows/test-build.yml
Labels: no-changelog

#1686 CODEOWNERS: update to match the frontend and backend teams
  .github/CODEOWNERS
Labels: chore, no-changelog

#1671 Docs: improves data proxy usage with custom config
  docusaurus/docs/how-to-guides/data-source-plugins/fetch-data-from-frontend.md
Labels: no-changelog

#1620 Chore: commenting out dry run
  .github/workflows/stale-branches.yml
Labels: no-changelog, ci

#1688 Build: Migrate to rollup and private workspaces
  libs/README.md
  libs/output/package.json
  libs/output/src/index.ts
  libs/output/tsconfig.json
  libs/version/package.json
  libs/version/src/index.ts
  libs/version/tsconfig.json
  nx.json
  package-lock.json
  package.json
  packages/create-plugin/package.json
  packages/eslint-plugin-plugins/package.json
  packages/plugin-e2e/package.json
  packages/plugin-types-bundler/package.json
  packages/sign-plugin/package.json
  rollup.config.ts
  tsconfig.base.json
  vitest.config.base.ts
Labels: patch, release

#1718 Chore: no need to create issues for stale branches
  .github/workflows/stale-branches.yml
Labels: no-changelog

#1691 Docs: adding "how to keep dashboards up to date" section
  docusaurus/docs/how-to-guides/data-source-plugins/include-dashboards.md
Labels: type/docs, no-changelog, documentation

#1720 Docs: Include changelog best practices and changelog generation option
  docusaurus/docs/publish-a-plugin/build-automation.md
  docusaurus/docs/publish-a-plugin/publishing-best-practices.md
Labels: no-changelog, documentation

#1732 CI: Install the locally built plugin-e2e in scaffolded plugins
  .github/workflows/ci.yml
Labels: no-changelog, ci

#1680 Fix: create-plugin common Webpack config types
  packages/create-plugin/src/utils/tests/utils.templates.test.ts
  packages/create-plugin/templates/common/.config/README.md
  packages/create-plugin/templates/common/.config/types/bundler-rules.d.ts
  packages/create-plugin/templates/common/.config/types/webpack-plugins.d.ts
  packages/create-plugin/templates/common/.config/webpack/utils.ts
  packages/create-plugin/templates/common/.config/webpack/webpack.config.ts
Labels: create-plugin, patch, release

#1736 Create Plugin: Scaffold bundle-stats with workflow_dispatch
  docusaurus/docs/get-started/set-up-development-environment.mdx
  packages/create-plugin/templates/github/workflows/bundle-stats.yml
  packages/create-plugin/templates/github/workflows/ci.yml
Labels: create-plugin, patch, release

#1737 Docs: Add section for testing routes with react router v6
  docusaurus/docs/shared/_migrate-to-react-router-v6.mdx
Labels: type/docs, no-changelog

#1740 chore: pins playwright/test because of version errors
  packages/create-plugin/templates/common/_package.json
Labels: patch, release

#1735 e2e: fixes TimeRange set function
  packages/plugin-e2e/src/models/components/TimeRange.ts
Labels: patch, release

#1741 fix: fixes playwright upgrade
  package-lock.json
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/common/playwright.config
  packages/plugin-e2e/package.json
  packages/plugin-e2e/playwright.config.ts
Labels: patch, release, type/bug

#1743 Chore: Bump dompurify
  package-lock.json
Labels: chore, no-changelog

#1744 Chore: Bump image-size
  package-lock.json
Labels: chore, no-changelog

#1749 chore: fixes unexpected flaky component tests (#1749)
  packages/create-plugin/templates/app/src/components/App/App.test.tsx
Labels: patch, release, tests

#1755 CI: Update workflows
  .github/workflows/check-labels.yml
  .github/workflows/ci.yml
  .github/workflows/deploy-to-developer-portal-dev.yml
  .github/workflows/deploy-to-developer-portal-prod.yml
  .github/workflows/lapo-create-pr.yml
  .github/workflows/lapo-generate-embeddings.yml
  .github/workflows/playwright.yml
  .github/workflows/test-build.yml
Labels: no-changelog, ci

#1756 CI: fix failing ci and playwright workflows
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
Labels: no-changelog, ci
