Repository grafana/plugin-tools, pull requests merged in 2025-03, with the labels that each got.

#1584 Add documentation, license, raise and issue links to the docs
  docusaurus/docs/reference/metadata.md
Labels: type/docs, no-changelog

#1599 Build: force installation of optional peer dependencies for CI
  package-lock.json
  package.json
Labels: chore, type/bug, no-changelog, github_actions

#1606 Create Plugin: Fix timeouts with canary e2e tests
  packages/create-plugin/templates/common/_package.json
Labels: dependencies, create-plugin, patch, release

#1496 Docs: Externally shared dashboard datasource plugin support
  docusaurus/docs/how-to-guides/data-source-plugins/add-support-for-externally-shared-dashboards.md
  docusaurus/docs/how-to-guides/data-source-plugins/convert-a-frontend-datasource-to-backend.md
Labels: type/docs, minor

#1614 Adding stale branches cleanup action
  .github/workflows/stale-branches.yml
Labels: no-changelog

#1615 Plugin E2E: Fix panel options group collapsable in 11.6.0
  .github/workflows/playwright.yml
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.advancedMode.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.basicMode.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/variableInterpolation.spec.ts
  packages/plugin-e2e/tests/as-admin-user/page-loading/goto.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelEdit.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelMenu.spec.ts
Labels: no-changelog, plugin-e2e

#1613 Chore: Reduce playwright reports retention days
  .github/workflows/ci.yml
  .github/workflows/playwright.yml
Labels: chore, no-changelog

#1616 Chore: fix highlighting in add-template-variables-doc
  docusaurus/docs/how-to-guides/data-source-plugins/add-support-for-variables.md
  package-lock.json
Labels: type/docs, chore, no-changelog

#1597 Feature: Consistent CLI output
  libs/README.md
  libs/output/README.md
  libs/output/src/index.mts
  libs/version/README.md
  libs/version/src/index.mts
  package-lock.json
  package.json
  packages/create-plugin/package.json
  packages/create-plugin/src/bin/run.ts
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/commands/generate/print-success-message.ts
  packages/create-plugin/src/commands/migrate.command.ts
  packages/create-plugin/src/commands/provisioning.command.ts
  packages/create-plugin/src/commands/update.command.ts
  packages/create-plugin/src/commands/update.migrate.command.ts
  packages/create-plugin/src/commands/update.standard.command.ts
  packages/create-plugin/src/commands/version.command.ts
  packages/create-plugin/src/constants.ts
  packages/create-plugin/src/utils/tests/utils.config.test.ts
  packages/create-plugin/src/utils/utils.config.ts
  packages/create-plugin/src/utils/utils.console.ts
  packages/create-plugin/src/utils/utils.templates.ts
  packages/create-plugin/src/utils/utils.version.ts
  packages/plugin-e2e/package.json
  packages/plugin-types-bundler/package.json
  packages/sign-plugin/package.json
  packages/sign-plugin/src/commands/sign.command.ts
  packages/sign-plugin/src/commands/version.command.ts
  packages/sign-plugin/src/utils/getVersion.ts
  packages/sign-plugin/src/utils/manifest.ts
  packages/sign-plugin/src/utils/utils.output.ts
  packages/sign-plugin/src/utils/utils.version.ts
  tsconfig.base.json
  tsup.config.ts
  vitest.config.base.ts
Labels: enhancement, create-plugin, sign-plugin, minor, release

#1619 Docs: Update readme
  README.md
Labels: type/docs, chore, no-changelog

#1628 Revert: Lerna to 8.1.9
  package-lock.json
  package.json
Labels: chore, no-changelog

#1643 CI: Add optionDependencies to devDependencies group
  .github/renovate.json5
Labels: no-changelog, ci

#1630 Integrate lapo docs into repository
  .github/workflows/lapo-create-pr.yml
  .github/workflows/lapo-generate-embeddings.yml
Labels: no-changelog
