Repository grafana/plugin-tools, pull requests merged in 2025-01, with the labels that each got.

#1414 feat: add create plugin version to sign request
  packages/sign-plugin/README.md
  packages/sign-plugin/src/commands/sign.command.ts
  packages/sign-plugin/src/utils/getCreatePluginVersion.ts
  packages/sign-plugin/src/utils/manifest.ts
Labels: no-changelog

#1436 Docs: Fix warnings about nested link tags in build logs
  docusaurus/docs/shared/create-plugin-backend.md
  docusaurus/docs/shared/create-plugin-frontend.md
Labels: type/docs, no-changelog

#1435 Website: Use .env files with Docusaurus config
  .github/workflows/deploy-to-developer-portal-dev.yml
  docusaurus/website/.env.development
  docusaurus/website/.env.production
  docusaurus/website/README.md
  docusaurus/website/docusaurus.config.base.ts
  docusaurus/website/docusaurus.config.dev.ts
  docusaurus/website/docusaurus.config.ts
  docusaurus/website/package.json
  docusaurus/website/sidebars.ts
  docusaurus/website/websiteRedirects.json
  package-lock.json
Labels: no-changelog, documentation

#1444 Sign Plugin: Remove console.log on failed version check
  packages/sign-plugin/src/utils/getCreatePluginVersion.ts
Labels: sign-plugin, patch, release

#1445 Chore: use vault to get slack webhook url
  .github/workflows/ci.yml
Labels: no-changelog

#1439 CI: Use NPX when scaffolding plugin
  .github/workflows/ci.yml
Labels: no-changelog, ci

#1438 Create Plugin: Support Yarn Berry
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/snippets/createplugin-migrate.yarn.md
  docusaurus/docs/snippets/createplugin-scaffold.yarn.md
  docusaurus/docs/snippets/createplugin-update-force.yarn.md
  docusaurus/docs/snippets/createplugin-update.yarn.md
  packages/create-plugin/README.md
  packages/create-plugin/src/commands/generate.command.ts
  packages/create-plugin/src/utils/utils.packageManager.ts
  packages/create-plugin/src/utils/utils.templates.ts
  packages/create-plugin/templates/common/gitignore
Labels: create-plugin, minor, release

#1440 Website: Use docusaurus/npm2yarn plugin
  docusaurus/docs/e2e-test-a-plugin/get-started.md
  docusaurus/docs/e2e-test-a-plugin/migrate-from-grafana-e2e.md
  docusaurus/docs/get-started/get-started.mdx
  docusaurus/docs/get-started/set-up-development-environment.mdx
  docusaurus/docs/how-to-guides/app-plugins/work-with-nested-plugins.md
  docusaurus/docs/migration-guides/migrate-from-toolkit.mdx
  docusaurus/docs/publish-a-plugin/package-a-plugin.md
  docusaurus/docs/reference/cli-commands.mdx
  docusaurus/docs/shared/_migrate-to-react-router-v6.mdx
  docusaurus/docs/shared/createplugin-build-ci.md
  docusaurus/docs/shared/createplugin-build-fe-dev.md
  docusaurus/docs/shared/createplugin-build-fe-prod.md
  docusaurus/docs/shared/createplugin-frontend-npm.md
  docusaurus/docs/shared/createplugin-install.md
  docusaurus/docs/shared/createplugin-migrate.md
  docusaurus/docs/shared/createplugin-scaffold.md
  docusaurus/docs/shared/createplugin-update-force.md
  docusaurus/docs/shared/createplugin-update.md
  docusaurus/docs/shared/docker-grafana-version.md
  docusaurus/docs/shared/plugin-e2e-install.md
  docusaurus/docs/shared/plugin-e2e-run-tests.md
  docusaurus/docs/shared/plugin-e2e-start-grafana.md
  docusaurus/docs/snippets/_category_.json
  docusaurus/docs/snippets/createplugin-build-ci.pnpm.md
  docusaurus/docs/snippets/createplugin-build-ci.yarn.md
  docusaurus/docs/snippets/createplugin-build-fe-dev.npm.md
  docusaurus/docs/snippets/createplugin-build-fe-dev.pnpm.md
  docusaurus/docs/snippets/createplugin-build-fe-dev.yarn.md
  docusaurus/docs/snippets/createplugin-build-fe-prod.pnpm.md
  docusaurus/docs/snippets/createplugin-build-fe-prod.yarn.md
  docusaurus/docs/snippets/createplugin-frontend-pnpm.md
  docusaurus/docs/snippets/createplugin-frontend-yarn.md
  docusaurus/docs/snippets/createplugin-install.npm.md
  docusaurus/docs/snippets/createplugin-install.pnpm.md
  docusaurus/docs/snippets/createplugin-migrate.pnpm.md
  docusaurus/docs/snippets/createplugin-migrate.yarn.md
  docusaurus/docs/snippets/createplugin-scaffold.pnpm.md
  docusaurus/docs/snippets/createplugin-scaffold.yarn.md
  docusaurus/docs/snippets/createplugin-update-force.pnpm.md
  docusaurus/docs/snippets/createplugin-update-force.yarn.md
  docusaurus/docs/snippets/createplugin-update.pnpm.md
  docusaurus/docs/snippets/createplugin-update.yarn.md
  docusaurus/docs/snippets/docker-grafana-version.pnpm.md
  docusaurus/docs/snippets/docker-grafana-version.yarn.md
  docusaurus/docs/snippets/plugin-e2e-install.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-install.yarn.md
  docusaurus/docs/snippets/plugin-e2e-run-tests.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-run-tests.yarn.md
  docusaurus/docs/snippets/plugin-e2e-start-grafana.pnpm.md
  docusaurus/docs/snippets/plugin-e2e-start-grafana.yarn.md
  docusaurus/website/docusaurus.config.ts
  docusaurus/website/package.json
  docusaurus/website/src/components/SyncCommand/SyncCommand.tsx
  docusaurus/website/src/css/custom.css
  package-lock.json
Labels: no-changelog, documentation

#1272 E2E: Improve support to interact with panel edit options
  .github/workflows/playwright.yml
  package-lock.json
  packages/plugin-e2e/docker-compose.yaml
  packages/plugin-e2e/src/index.ts
  packages/plugin-e2e/src/matchers/toBeChecked.ts
  packages/plugin-e2e/src/matchers/toHaveChecked.ts
  packages/plugin-e2e/src/matchers/toHaveColor.ts
  packages/plugin-e2e/src/matchers/toHaveSelected.ts
  packages/plugin-e2e/src/models/components/ColorPicker.ts
  packages/plugin-e2e/src/models/components/ComponentBase.ts
  packages/plugin-e2e/src/models/components/MultiSelect.ts
  packages/plugin-e2e/src/models/components/PanelEditOptionsGroup.ts
  packages/plugin-e2e/src/models/components/RadioGroup.ts
  packages/plugin-e2e/src/models/components/Select.ts
  packages/plugin-e2e/src/models/components/Switch.ts
  packages/plugin-e2e/src/models/components/UnitPicker.ts
  packages/plugin-e2e/src/models/components/types.ts
  packages/plugin-e2e/src/models/pages/GrafanaPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/src/models/utils.ts
  packages/plugin-e2e/src/selectors/versionedConstants.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelEdit.spec.ts
Labels: minor, release, plugin-e2e

#1457 CI: Revert no of jobs limit change
  .github/workflows/playwright.yml
Labels: no-changelog

#1405 Plugin E2E: Use custom data source for internal tests
  .github/workflows/playwright.yml
  package-lock.json
  packages/plugin-e2e/CONTRIBUTING.md
  packages/plugin-e2e/docker-compose.yaml
  packages/plugin-e2e/package.json
  packages/plugin-e2e/playwright.config.ts
  packages/plugin-e2e/provisioning/alerting/testdatasource.yml
  packages/plugin-e2e/provisioning/dashboards/redshift.json
  packages/plugin-e2e/provisioning/dashboards/testdatasource-annotations.json
  packages/plugin-e2e/provisioning/dashboards/testdatasource.json
  packages/plugin-e2e/provisioning/datasources/google-sheets-datasource-jwt.yaml
  packages/plugin-e2e/provisioning/datasources/redshift.yaml
  packages/plugin-e2e/provisioning/datasources/testdatasource.yaml
  packages/plugin-e2e/src/fixtures/isFeatureToggleEnabled.ts
  packages/plugin-e2e/src/models/pages/DashboardPage.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/annotations/annotationQueryRunner.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/config-editor/configEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/dashboards/dashboard.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/data-assertions/dataAssertion.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/explore/queryEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.async.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.sync.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.tlsEnabled.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/feature-toggles/queryEditor.tlsNotEnabled.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/mocks/resource.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/query-editor/queryEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/customVariableQueryRunner.integration.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/variableEditor.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/variables/variableInterpolation.spec.ts
  packages/plugin-e2e/tests/as-admin-user/page-loading/goto.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelEdit.spec.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelMenu.spec.ts
Labels: no-changelog

#1462 E2E: Added missing APIs while writing tests for panel editor
  packages/plugin-e2e/src/models/components/PanelEditOptionsGroup.ts
  packages/plugin-e2e/src/models/pages/PanelEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/panel/panelEdit.spec.ts
Labels: minor, release, plugin-e2e

#1394 Docs: add note forbidding allowance of user input of JS
  docusaurus/docs/get-started/best-practices.md
Labels: type/docs, no-changelog

#1478 Chore: Improve ESlint config and fix NX config
  .eslintignore
  eslint.config.js
  nx.json
Labels: chore, no-changelog, ci

#1468 Docs: Add article on how to implement runtime checks
  docusaurus/docs/how-to-guides/runtime-checks.md
Labels: no-changelog

#1483 Plugin E2E: Fix datasource picker root locator
  packages/plugin-e2e/src/models/components/DataSourcePicker.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.spec.ts
Labels: patch, release

#1475 Docs: Add section about provenance attestation for github pipelines
  docusaurus/docs/publish-a-plugin/build-automation.md
Labels: type/docs, no-changelog, documentation

#1494 Docs: Describe compatibility strategy in best-practices doc
  docusaurus/docs/e2e-test-a-plugin/ci.md
  docusaurus/docs/get-started/best-practices.md
  docusaurus/docs/how-to-guides/runtime-checks.md
Labels: no-changelog

#1498 Remove reference to streaming example from docs
  docusaurus/docs/get-started/best-practices.md
  docusaurus/docs/key-concepts/backend-plugins/index.md
  docusaurus/docs/tutorials/build-a-streaming-data-source-plugin.md
Labels: no-changelog, documentation

#1502 CreatePlugin: Update that panel plugin template uses new panel edit options
  packages/create-plugin/templates/common/_package.json
  packages/create-plugin/templates/panel/tests/panel.spec.ts
Labels: patch, release

#1490 Plugin E2E: Support advanced query mode in alert rules
  docusaurus/docs/e2e-test-a-plugin/test-a-data-source-plugin/alert-queries.md
  package-lock.json
  packages/plugin-e2e/src/models/pages/AlertRuleEditPage.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.advancedMode.spec.ts
  packages/plugin-e2e/tests/as-admin-user/datasource/alerting/alerting.basicMode.spec.ts
Labels: minor, release
